//! vex-world -- a procedural overworld assembled by wave function collapse.
//!
//! A MAP_W x MAP_H tile map is generated by starting every cell as "any tile"
//! and repeatedly collapsing the cell with the fewest options left, propagating
//! the constraint to its neighbours. Tiles are opaque 16x16 palette bitmaps
//! blitted straight into the framebuffer, so a frame is one blit per visible
//! tile -- about 200, not one per map cell.
const std = @import("std");
const vex = @import("vex");
const cfg = @import("cfg");

// -- palette ----------------------------------------------------------------
// JONK 16, applied over the console's default SWEETIE-16 in boot().
//
// The art names colours by role rather than by index, so trying another palette
// means editing this block and the table in boot(), and nothing else. That is
// not tidiness: the roles encode relationships, not preferences. Deep water has
// to be exactly one step darker than shallows, forest darker than grass, and a
// crest on one terrain has to be the body tone of the next. Written as raw
// indices the art hides all of that, and swapping palettes then silently turns
// grass into steel blue and snow into dark brown -- which is exactly what
// happened to the first version of this file.
const JONK16 = [16]u32{
    0x242e36, 0x455951, 0x798766, 0xb7bca2,
    0xd6d6d6, 0xf4f0ea, 0x6988a1, 0xa1b0be,
    0x595b7c, 0x95819d, 0xc9a5a9, 0xf4dec2,
    0x704f4f, 0xb7635b, 0xe39669, 0xebc790,
};

/// Index 0 is reserved and never appears in tile art: it is the blit
/// transparency key for the transition bands, so a terrain pixel painted 0
/// would punch a hole in the map.
const C = struct {
    // water, deepest first. A crest tone is the next depth's body tone, so a
    // shoreline ramps continuously instead of stepping.
    const water_deep: u8 = 8; // #595b7c muted indigo
    const water: u8 = 6; // #6988a1 steel blue
    const water_crest: u8 = 7; // #a1b0be pale blue
    const water_channel: u8 = 9; // #95819d, a lighter deep
    const water_deepest: u8 = 1; // #455951 dark slate
    const shoal: u8 = 15; // #ebc790, sand showing through

    const grass: u8 = 2; // #798766 olive
    const grass_light: u8 = 3; // #b7bca2 pale sage
    const flower: u8 = 11; // #f4dec2 cream
    const forest: u8 = 1; // #455951 dark slate green
    const forest_light: u8 = 2; // #798766 olive, same family as the grass
    // Deeper in. No new palette entry: the tier is carried by how much canopy
    // each patch holds, not by a third green. An earlier attempt used the brown
    // (#704f4f) and read as mud at one pixel per tile -- a different biome, not
    // a deeper wood. The dither between these two greens is the whole signal.
    const forest_deep: u8 = 1; // #455951, the same dark green, barely dappled

    const sand: u8 = 15; // #ebc790
    const sand_dark: u8 = 14; // #e39669

    const rock: u8 = 9; // #95819d dusty purple
    const rock_light: u8 = 4; // #d6d6d6
    const rock_dark: u8 = 12; // #704f4f
    // The two tiers above the first and the peak between them and snow. A ramp
    // in *value* from the purple up to near-white is what makes the climb
    // legible, and there are only 16 slots to spend, so the tiers re-mix tones
    // already in use rather than claiming new ones. An earlier attempt gave the
    // scree the sand orange (#e39669) and high ground read as beach.
    const rock_high: u8 = 4; // #d6d6d6 pale stone
    // Dark, not pale: the top of a range has to be the most visible part
    // of it, and the scree below already owns the pale end of the ramp.
    const peak: u8 = 12; // #704f4f dark stone

    const snow: u8 = 5; // #f4f0ea
    const snow_shade: u8 = 4; // #d6d6d6
    const snow_tint: u8 = 7; // #a1b0be

    const roof: u8 = 13; // #b7635b terracotta
    const wall: u8 = 4; // #d6d6d6
    const timber: u8 = 12; // #704f4f

    const ui_bg: u8 = 0; // #242e36
    const ui_dim: u8 = 1; // #455951
    const ui_text: u8 = 4; // #d6d6d6
    const ui_bright: u8 = 5; // #f4f0ea
    const ui_fill: u8 = 2; // #798766
};

// -- world geometry ---------------------------------------------------------

const T: usize = 16; // tile edge, px
const MAP_W: usize = 320;
const MAP_H: usize = 160;
const CELLS: usize = MAP_W * MAP_H;

const VIEW_W: i32 = vex.WIDTH / @as(i32, @intCast(T)); // 20
const VIEW_H: i32 = (vex.HEIGHT - 20) / @as(i32, @intCast(T)); // 10
const HUD_Y: i32 = vex.HEIGHT - 20;
const MAX_CAM_X: i32 = @as(i32, @intCast(MAP_W * T)) - vex.WIDTH;
const MAX_CAM_Y: i32 = @as(i32, @intCast(MAP_H * T)) - VIEW_H * @as(i32, @intCast(T));

/// Collapses per frame while generating, as a fraction of the map rather than a
/// fixed number. A flat budget does not survive a resize: at 96 per frame the
/// 51,200-cell map needed 533 frames -- nine seconds -- even though the whole
/// solve costs tens of milliseconds. Dividing the map keeps the "watch it
/// appear" pacing at roughly half a second whatever the size.
const GENERATE_PER_FRAME: usize = @max(64, CELLS / 32);

// -- tiles ------------------------------------------------------------------

const Kind = enum(u8) { deep, shallow, sand, grass, forest, forest_deep, rock, rock_high, peak, snow, ruins };

const DEEP: u8 = 0;
const SHALLOW: u8 = 1;
const SAND: u8 = 2;
const GRASS: u8 = 3;
const FOREST: u8 = 4;
/// Second forest tier. Two levels rather than one so the climb out of the
/// plains reads as a gradient instead of a single step to a flat green mass.
const FOREST_DEEP: u8 = 5;
/// Rock is split three ways, low to high, for the same reason: at one level
/// the highlands were a single flat purple that gave no sense of rising.
const ROCK: u8 = 6;
const ROCK_HIGH: u8 = 7;
const PEAK: u8 = 8;
const SNOW: u8 = 9;
const RUINS: u8 = 10;
const TILE_COUNT: usize = 11;
const ALL_TILES: u16 = (@as(u16, 1) << TILE_COUNT) - 1;

/// How many looks each tile kind gets, chosen per map position at draw time so
/// a kind is never the same texture twice in a row. The visible repeat period
/// goes as T * sqrt(VARIANTS), so 4 repeats about every 32px and 8 about every
/// 45px -- enough that grass and sand stop reading as wallpaper.
///
/// Costs 2 KB per variant across art and bands, so this is the knob to turn
/// back down if the wasm gets too big. It only helps the *noise* tiles: ruins
/// needed a different fix entirely, see tileArt.
const VARIANTS: usize = 8;

/// `only` is a hand-written neighbour whitelist: a tile with one may only
/// touch the tiles in it. Everything else falls back to the class rule, so
/// plain terrain blends by elevation while ruins stay put.
const Tile = struct {
    kind: Kind,
    cls: u8, // elevation band: neighbouring classes must be within 1
    weight: u16, // relative pick weight once a cell collapses
    only: u16, // 0 = use the class rule
    name: [:0]const u8,
    /// Representative colour for the one-pixel-per-tile overview. The art's
    /// body tone rather than a corner pixel, which could be a wave crest or a
    /// speckle and would make the map flicker between shades of the same sea.
    map: u8,
    /// [variant][frame]. The frame index is the animation phase and only the
    /// water tiles use it; the variant is picked per map position at draw time
    /// so the same tile kind does not stamp one identical texture everywhere.
    art: [VARIANTS][2][T * T]u8 = @splat(@splat(@splat(0))),
};

const TILES: [TILE_COUNT]Tile = blk: {
    var list: [TILE_COUNT]Tile = .{
        .{ .kind = .deep, .cls = 0, .weight = 6, .only = 0, .name = "DEEP SEA", .map = C.water_deep },
        .{ .kind = .shallow, .cls = 1, .weight = 6, .only = 0, .name = "SHALLOWS", .map = C.water },
        .{ .kind = .sand, .cls = 2, .weight = 5, .only = 0, .name = "BEACH", .map = C.sand },
        .{ .kind = .grass, .cls = 3, .weight = 2500, .only = 0, .name = "PLAINS", .map = C.grass },
        .{ .kind = .forest, .cls = 4, .weight = 8, .only = 0, .name = "FOREST", .map = C.forest },
        .{ .kind = .forest_deep, .cls = 5, .weight = 6, .only = 0, .name = "DEEP FOREST", .map = C.forest_deep },
        .{ .kind = .rock, .cls = 6, .weight = 4, .only = 0, .name = "HIGHLANDS", .map = C.rock },
        .{ .kind = .rock_high, .cls = 7, .weight = 3, .only = 0, .name = "HIGH SCREE", .map = C.rock_high },
        .{ .kind = .peak, .cls = 8, .weight = 2, .only = 0, .name = "PEAKS", .map = C.peak },
        .{ .kind = .snow, .cls = 9, .weight = 2, .only = 0, .name = "SNOWCAP", .map = C.snow },
        // A landmark: same elevation band as the plains, so it stays in the
        // settled lowlands instead of speckling the mountains.
        //
        // SAND is deliberately *not* in the whitelist. Ruins can only be
        // picked where wantClass returns the plains class, which is the bottom
        // fifth of the land range -- a thin ring that follows the coast. With
        // beach allowed, every ruin in the world landed in that ring and the
        // result was a line of houses strung along the shoreline, because a
        // contour band *is* a coastline. Excluding sand forces them a tile
        // inland, which is where a ruin belongs anyway.
        //
        // The rarity is set by the plains' weight rather than ruins': both are
        // class 3, so they share a pick pool and the odds are ruins:plains.
        // At 1:100 that was 162 ruins on one map -- enough to read as a
        // pattern rather than a landmark. 1:400 puts it near a dozen.
        .{ .kind = .ruins, .cls = 3, .weight = 1, .only = bit(GRASS) | bit(FOREST) | bit(FOREST_DEEP) | bit(RUINS), .name = "RUINS", .map = C.roof },
    };
    for (&list) |*t| for (0..2) |f| for (0..VARIANTS) |v| {
        t.art[v][f] = tileArt(t.kind, f, v);
    };
    break :blk list;
};

fn bit(t: u8) u16 {
    return @as(u16, 1) << @intCast(t);
}

/// May `a` sit next to `b`? Whitelists win over the elevation rule, and are
/// checked on both sides so the relation stays symmetric.
fn adjacent(a: u8, b: u8) bool {
    if (TILES[a].only != 0) return TILES[a].only & bit(b) != 0;
    if (TILES[b].only != 0) return TILES[b].only & bit(a) != 0;
    return @abs(@as(i32, TILES[a].cls) - @as(i32, TILES[b].cls)) <= 1;
}

const DX = [4]i32{ 0, 1, 0, -1 };
const DY = [4]i32{ -1, 0, 1, 0 };
const OPP = [4]usize{ 2, 3, 0, 1 };

/// `ALLOWED[dir][tile]` = every tile that may touch it on that side.
const ALLOWED: [4][TILE_COUNT]u16 = blk: {
    // This is a comptime triple loop over dirs x tiles x tiles, so the branch
    // budget has to cover it. Scaled off TILE_COUNT rather than pinned to a
    // number, because adding tiles is exactly the edit that overruns it and the
    // error points at the loop rather than at the tile table.
    @setEvalBranchQuota(64 * TILE_COUNT * TILE_COUNT);
    var out: [4][TILE_COUNT]u16 = @splat(@splat(0));
    for (0..4) |d| for (0..TILE_COUNT) |a| for (0..TILE_COUNT) |b| {
        if (adjacent(@intCast(a), @intCast(b))) out[d][a] |= @as(u16, 1) << @intCast(b);
    };
    break :blk out;
};

// -- tile art ---------------------------------------------------------------
// Every tile is generated at comptime from a small hand-written pattern, so
// the set costs no source bytes beyond the rules above.

const NP: usize = T * T;

fn hash(x: u32, y: u32, s: u32) u32 {
    var v = x *% 0x9E3779B1 +% y *% 0x85EBCA77 +% s *% 0xC2B2AE3D;
    v ^= v >> 15;
    v *%= 0x2545F491;
    v ^= v >> 13;
    return v;
}

/// Spacing of the wave crests, in the `x + y` sum. It must divide T: draw()
/// animates the sea by folding the tile's map position into `phase`, so the
/// tile term only cancels when the period is a factor of the tile size. With a
/// period that does not divide T every tile's wave is shifted by a different
/// amount and the water breaks up along the grid instead of rolling as one body.
const CREST_PERIOD: usize = 16;

/// One period of a sine, sampled by position to bend the crests.
///
/// A straight, evenly spaced 45-degree line reads as hatching, not water: the
/// regularity is the problem, not the colour. Warping the crest coordinate
/// turns it into a curve and, because the warp is steeper in some places than
/// others, the crests also bunch and spread instead of marching in lockstep.
///
/// The warp has to be periodic with the tile. Sampling this table by local
/// position makes it exactly so, which is what keeps the curves continuous
/// across tile edges -- a warp that is not periodic tears the sea along the
/// grid, the same failure the crest period has to avoid.
const SINE = [16]i32{ 0, 2, 4, 5, 6, 5, 4, 2, 0, -2, -4, -5, -6, -5, -4, -2 };

/// How far to push the crest at this pixel, in px. Summed over both axes so
/// the crest bends along its length instead of merely shifting sideways.
///
/// The 1/3 divisor sets the bend. Straight ahead of this, 1/2 bends harder but
/// the crests curl apart into scattered hooks and stop reading as a swell; 1/3
/// keeps them as continuous lines that roll.
fn waveWarp(x: usize, y: usize) i32 {
    return @divTrunc(SINE[x % SINE.len] + SINE[y % SINE.len], 3);
}

fn crest(x: usize, y: usize, phase: usize) bool {
    const u: i32 = @as(i32, @intCast(x + y)) + waveWarp(x, y) + @as(i32, @intCast(phase));
    return @mod(u, @as(i32, @intCast(CREST_PERIOD))) == 0;
}

/// Water tones, deepest first. Deliberately a contiguous ramp: DEEP_CREST is
/// exactly SHALLOW's body, so the two tiles differ by one step and a shoreline
/// reads as shoaling water rather than as two unrelated colours meeting.
const DEEP_BODY: u8 = C.water_deep;
const DEEP_CREST: u8 = C.water;
const SHALLOW_BODY: u8 = C.water;
const SHALLOW_CREST: u8 = C.water_crest;

// -- transition bands --------------------------------------------------------
// Where two kinds meet, the tile boundary is a hard 16px seam. A band dithers
// the two terrains into each other across that edge.
//
// The band has to carry *both* sides. Carrying only the neighbour's texture --
// the obvious cheap version -- stamps one terrain's grain over the other and
// reads as a line laid on top of the map rather than a transition. A full
// per-pair tileset would be the other extreme, and still could not cover a tile
// with three different neighbours, so the blend stays an overlay.

/// How far the blend reaches in from the edge, in px.
const BAND: usize = 8;

/// 4x4 ordered dither, the classic pixel-art crosshatch. Deliberately a fixed
/// matrix and not noise: the regular weave is what makes the fade look
/// deliberate rather than dirty.
const BAYER4 = [16]u8{ 0, 8, 2, 10, 12, 4, 14, 6, 3, 11, 1, 9, 15, 7, 13, 5 };

/// `other` dithered in over the half of the tile facing side `dir`, where
/// `other` is the neighbour that way, drawn as `variant`. 0 means "let this
/// tile show through"; no art uses palette 0, so 0 is also the blit key.
///
/// The blend only covers the half of the tile nearest the neighbour, and only
/// this tile draws. Blending the whole tile, or blending on both sides of a
/// seam, makes the two bands overlap across the whole boundary: the transition
/// comes out 16px wide with each terrain visible on the far side of the other.
///
/// `variant` is the *neighbour's* variant and is not optional. Bands keyed on
/// kind alone made the squares show: the blend carried variant 0's texture
/// while the neighbouring tile drew a random variant, so every seam mismatched,
/// and one wobble pattern repeated with period 16 across the world. Anywhere
/// three terrains interleave -- beach, shallows, deep sea -- the seams are
/// frequent enough that the shared wobble read as a 16px grid.
fn bandArt(other: u8, dir: usize, variant: usize) [NP]u8 {
    @setEvalBranchQuota(200_000);
    const salt: u32 = 0xB0 +% @as(u32, other) * 31 +% @as(u32, @intCast(variant)) * 7;
    var px: [NP]u8 = @splat(0);
    for (0..T) |yy| for (0..T) |xx| {
        // how far in from the facing edge this pixel is
        const along: usize = switch (dir) {
            0 => yy, // north
            1 => T - 1 - xx, // east
            2 => T - 1 - yy, // south
            else => xx, // west
        };
        if (along >= BAND) continue;
        const wob: i32 = @as(i32, @intCast(hash(xx / 2, yy / 2, salt) % 5)) - 2;
        // Clamp at 0, do not skip. `along` is 0 on the shared edge with the
        // neighbour, and a negative wobble there skipped the pixel entirely,
        // letting the base tile show through -- a bare seam line across the one
        // place the two terrains are supposed to actually meet. The wobble may
        // only eat into the band from the inside.
        const t: i32 = @max(0, @as(i32, @intCast(along)) + wob);
        if (t >= BAND) continue; // wobble pushed it out of the band
        // 0 = all neighbour (on the edge), BAND = all this tile (back inside)
        if (BAYER4[(yy % 4) * 4 + (xx % 4)] * BAND >= t * 16) {
            px[yy * T + xx] = TILES[other].art[variant][0][yy * T + xx];
        }
    };
    return px;
}

/// Which sides draw a band: east and south only.
///
/// A seam must be blended exactly once. With all four sides enabled, the sand
/// tile west of a grass tile fades grass in across its east half *and* the
/// grass tile fades sand in across its west half, so the two overlap across
/// the whole boundary: green spikes up to full at the beach, collapses back to
/// bare sand inside the plains, then recovers. That reads as green being
/// denser on the beach side than the plains side, which is exactly backwards.
///
/// Restricting to east and south makes the tile earlier in row-major order the
/// sole owner of each seam, so the blend is a single ramp with no second
/// counter-ramp fighting it.
const BAND_DIRS = [2]usize{ 1, 2 }; // east, south

/// Ruins are excluded because they are a building standing *on* the plains, not
/// a terrain of their own: blending them would dither grass through the walls
/// and scatter roof onto the grass next door.
fn bandsWith(t: u8) bool {
    return t != RUINS;
}

fn dirSlot(d: usize) usize {
    const i: usize = if (d == BAND_DIRS[0]) 0 else 1;
    return i;
}

const BANDS: [TILE_COUNT][BAND_DIRS.len][VARIANTS][NP]u8 = blk: {
    var out: [TILE_COUNT][BAND_DIRS.len][VARIANTS][NP]u8 = undefined;
    for (0..TILE_COUNT) |b| for (BAND_DIRS, 0..) |d, di| for (0..VARIANTS) |v| {
        out[b][di][v] = bandArt(@intCast(b), d, v);
    };
    break :blk out;
};

fn tileArt(comptime kind: Kind, comptime phase: usize, comptime variant: usize) [NP]u8 {
    @setEvalBranchQuota(12_000_000);
    var px: [NP]u8 = @splat(0);
    for (0..T) |yy| for (0..T) |xx| {
        const n = hash(@intCast(xx), @intCast(yy), @as(u32, @intFromEnum(kind)) * 977 +%
            @as(u32, @intCast(variant)) * 331 +% phase * 7 +% 1);
        // Noise for the wave itself, deliberately *not* seeded by `kind` or
        // `variant`: both water tiles have to break their crest along the same
        // lines, or the ripple runs on across a DEEP/SHALLOWS join but its gaps
        // do not, and any two water tiles can meet at any variant pair.
        const w = hash(@intCast(xx), @intCast(yy), phase * 7 +% 1);
        // Body noise for the water tiles. Per-pixel, and deliberately *not*
        // seeded by `phase`: a coarse grain at this contrast reads as a grid of
        // blocks (4x4 blotches of 8 against 9 were plainly a checkerboard), and
        // a phase-seeded one would make the texture shimmer with the wave. Fine
        // grain only works at low contrast -- which is why the forest's
        // three-tone dither passes and this did not.
        const d = hash(xx, yy, 0xDEE9 +% @as(u32, @intFromEnum(kind)) * 13 +%
            @as(u32, @intCast(variant)) * 5);
        var c: u8 = 8;
        switch (kind) {
            // Water is a depth ramp: DEEP sits on 9 and SHALLOWS on 10, one
            // step apart, so a shoreline reads as shoaling rather than as dark
            // paint meeting light paint. An earlier DEEP was flat 8, several
            // steps from SHALLOWS 9, and read as a void with lines drawn on it.
            // The mottle is what stops either of them looking like a solid fill.
            .deep => c = if (d % 11 == 0) C.water_channel else if (d % 37 == 0) C.water_deepest else DEEP_BODY,
            .shallow => c = if (d % 11 == 0) DEEP_BODY else if (d % 29 == 0) C.shoal else SHALLOW_BODY,
            .sand => c = if (n % 17 == 0) C.sand_dark else if (n % 11 == 0) C.flower else C.sand,
            .grass => c = if (n % 53 == 0) C.flower else if (n % 19 == 0) C.grass_light else C.grass,
            // Forest is dither, not drawn crowns. An earlier version painted
            // round canopies, but any shape big enough to read as a tree is
            // also big enough that a per-tile variant tears it at the tile
            // border -- and a few round blobs sitting on light green read as
            // bushes, not forest.
            //
            // Two layers, because each alone was wrong. Pure 2x2 blocks at this
            // contrast were a visible lattice, and that lattice sits inside
            // *every* variant, so adding variants only reproduced it. Pure
            // per-pixel dither went the other way and the tile just read as
            // darker grass, with no canopy to it. So: a 2x2 block picks how much
            // dark canopy a patch holds, and a per-pixel dither lays the pixels
            // down inside it. The dither breaks the block edges, the blocks give
            // the dither shade to vary across, and neither is visible alone.
            .forest, .forest_deep => {
                const b = hash(xx / 2, yy / 2, 0x5EED +% @as(u32, @intCast(variant)) +%
                    @as(u32, @intFromEnum(kind)) * 13);
                // how much of the patch is dark canopy: 7 is the shaded tone
                const dark: u32 = switch (b % 3) {
                    0 => 8, // deep shade
                    1 => 5, // even
                    else => 2, // sunlit, mostly showing the grass beneath
                };
                // The two forest tiers share this dither and differ only in how
                // much canopy each patch carries, which is the whole point of
                // the split: same texture, denser, so the eye reads "deeper
                // into the trees" rather than "a different green appeared". The
                // deep tier never shows the grass through, so a whole hillside
                // of it is unbroken canopy where the tier below is dappled.
                // Denser canopy in the deep tier: barely any grass left to
                // show through, so a whole hillside of it is unbroken where
                // the tier below is dappled.
                const d2: u32 = if (kind == .forest_deep) @min(dark + 4, 10) else dark;
                c = if (n % 10 < d2) C.forest else C.forest_light;
            },
            // Two rock tiers from one speckle, so the climb reads as one
            // material getting paler rather than two unrelated textures.
            .rock, .rock_high => {
                c = if (n % 13 == 0) C.rock_light else if (n % 19 == 0) C.rock_dark else C.rock;
                // paler, and the dark fissures thin out
                if (kind == .rock_high) c = if (n % 11 == 0) C.rock else C.rock_high;
            },
            // Peaks are drawn, not speckled. Everything else in the set is
            // noise at three scales, and a mountain made of noise is just a
            // pale patch -- which is exactly how the first version read: PEAKS
            // were the palest thing on the map and dissolved into the scree
            // below them, so the top of a range was the least visible part of
            // it.
            //
            // Instead: dark stone, as one or two upward-pointing ridges. The
            // shape does the work a colour ramp cannot here -- a range should
            // read as a *profile*, and one lit flank per ridge is what makes a
            // triangle look like a solid with a top rather than a shape drawn on
            // a flat tile. Dark also inverts the value order, so the peak is
            // now the highest-contrast thing up there instead of the least.
            .peak => {
                const vy: u32 = @intCast(yy);
                const vx: u32 = @intCast(xx);
                const ridges = 1 + hash(@intCast(variant), 7, 0xBEEF) % 2;
                c = C.rock_dark; // bare ground between the ridges
                for (0..ridges) |r| {
                    const h = hash(@intCast(r), @intCast(variant), 0xC0FFEE);
                    const cx: u32 = 3 + h % 10; // apex column
                    const half: u32 = 4 + (h >> 6) % 4; // half-width at the base
                    const top: u32 = (h >> 12) % 5; // where the apex sits
                    const depth: u32 = 8 + (h >> 18) % 5; // how far down it runs
                    if (vy < top or vy >= top + depth) continue;
                    // the cone widens as it descends, so the flank is a slope
                    const reach = (vy - top) * half / depth;
                    const dx = if (vx >= cx) vx - cx else cx - vx;
                    if (dx > reach) continue;
                    // The right flank catches the light. Both flanks have to
                    // differ from the background or the shadowed one vanishes
                    // into it and the cone reads as a sliver: an earlier
                    // version shaded the left flank with the same dark as the
                    // ground and drew a wedge, not a mountain.
                    c = if (vx >= cx) C.rock_light else C.rock;
                }
            },
            .snow => c = if (n % 9 == 0) C.snow_shade else if (n % 23 == 0) C.snow_tint else C.snow,
            // Ruins are the one tile in the set that is not noise, which made
            // them the one tile variants did nothing for: every ruin drew the
            // same house in the same place, so a village came out as a row of
            // photocopies. Buildings may vary freely, unlike the water's wave --
            // nothing has to line up with a neighbour across the tile edge, so
            // each gets its own plan. A building does get cut off at the edge
            // if it lands there, which is fine; it is a structure on a 16px plot.
            .ruins => {
                c = if (n % 19 == 0) C.grass_light else C.grass;
                switch (variant % 4) {
                    0 => { // cottage, gabled roof and a door
                        if (xx >= 3 and xx <= 12 and yy >= 5 and yy <= 11) {
                            c = if (yy <= 7) C.roof else if (yy == 11 or xx == 3 or xx == 12) C.timber else C.wall;
                            if (yy == 9 and xx == 7) c = C.timber;
                        }
                    },
                    1 => { // squat tower, crenellated
                        if (xx >= 5 and xx <= 10 and yy >= 4 and yy <= 12) {
                            c = if (yy == 4 or (yy == 5 and (xx == 5 or xx == 10))) C.timber else C.wall;
                            if (yy >= 7 and yy <= 9 and (xx == 7 or xx == 8)) c = C.timber;
                        }
                    },
                    2 => { // a collapsed wall, roof long gone
                        if (xx >= 2 and xx <= 13 and yy >= 7 and yy <= 10) {
                            if ((xx * 3 + yy * 5) % 7 != 0) c = if (yy == 7) C.roof else C.wall;
                            if (yy == 10) c = C.timber;
                        }
                    },
                    else => { // two low sheds
                        if ((xx >= 2 and xx <= 6 and yy >= 8 and yy <= 11) or
                            (xx >= 9 and xx <= 13 and yy >= 5 and yy <= 8))
                        {
                            c = if (yy == 8 or yy == 5) C.roof else C.wall;
                        }
                    },
                }
            },
        }
        // The crest goes on top of the mottled body, for both water tiles, and
        // always along the same `crest` lines -- that shared wave is what makes
        // a DEEP/SHALLOWS seam read as one body of water. DEEP_CREST is exactly
        // SHALLOW's body tone, so the ramp is continuous across the join: 9
        // deep body, 10 deep crest / shallow body, 11 shallow crest.
        if (kind == .deep or kind == .shallow) {
            if (crest(xx, yy, phase) and w % 2 == 0) {
                c = if (kind == .deep) DEEP_CREST else SHALLOW_CREST;
            }
        }
        px[yy * T + xx] = c;
    };
    return px;
}

// -- target field -----------------------------------------------------------
// The adjacency rules alone give a world of static: every cell is as likely to
// be sea as mountains, and the rules only forbid the jumps in between. So the
// collapse is *aimed* -- a smooth noise field decides the elevation each cell
// would like, and a cell takes the allowed tile closest to it. The rules still
// have the final word, which is what keeps the result consistent.

/// Sea level for the world being generated, jittered per seed so no two worlds
/// have the same amount of ocean.
var sea: f32 = 0.40;

fn lerp(a: f32, b: f32, t: f32) f32 {
    return a + (b - a) * t;
}

/// How high cell `i` wants to be, 0..1.
///
/// Four octaves, each halving in amplitude, because the straight beaches were
/// not a missing detail problem -- they were an interpolation problem. Within
/// one lattice cell the field is bilinear, so its contours are piecewise
/// straight, and at 6x4 across 320x160 a single straight run reached ~50 tiles.
/// More octaves put detail at every scale, so the eye stops reading the shape
/// as a blob and the straight segments become shorter than the interesting
/// bends around them.
const OCTAVES = [_]struct { w: usize, h: usize, amp: f32 }{
    .{ .w = 6, .h = 4, .amp = 0.53 },
    .{ .w = 13, .h = 8, .amp = 0.27 },
    .{ .w = 25, .h = 16, .amp = 0.13 },
    .{ .w = 49, .h = 32, .amp = 0.07 },
};

/// Offsets of each octave inside `oct_pool`.
const OCT_OFF = blk: {
    var off: [OCTAVES.len]usize = undefined;
    var at: usize = 0;
    for (OCTAVES, 0..) |o, k| {
        off[k] = at;
        at += o.w * o.h;
    }
    break :blk off;
};

const OCT_POOL: usize = OCT_OFF[OCTAVES.len - 1] + OCTAVES[OCTAVES.len - 1].w * OCTAVES[OCTAVES.len - 1].h;
var oct_pool: [OCT_POOL]f32 = undefined;

/// How far the warp can pull a sample point, as a fraction of the map. This is
/// the other half of the fix: octaves alone give detail but keep every
/// contour's overall direction, so coastlines still trace the lattice. Warping
/// bends them. Kept small on purpose -- a large warp folds the field over
/// itself and puts inland lakes in the wrong place.
const WARP_AMOUNT: f32 = 0.18;

var height: [CELLS]f32 = @splat(0);
var height_salt: u32 = 0;

fn buildHeight(salt: u32) void {
    for (OCTAVES, 0..) |o, k| {
        for (0..o.w * o.h) |i| {
            oct_pool[OCT_OFF[k] + i] = noiseVal(@intCast(i % o.w), @intCast(i / o.w), salt +% @as(u32, @intCast(k)) *% 0x9E37);
        }
    }
    var peak: f32 = 0;
    for (0..MAP_H) |y| for (0..MAP_W) |x| {
        const bx = @as(f32, @floatFromInt(x)) / @as(f32, @floatFromInt(MAP_W - 1));
        const by = @as(f32, @floatFromInt(y)) / @as(f32, @floatFromInt(MAP_H - 1));
        const fall = edgeFall(bx, by) + landMask(bx, by);
        // Warp first, then sample the stack at the displaced point. The warp
        // itself comes from the coarse octave sampled in two far-apart places,
        // so x and y displace independently instead of sliding along one line.
        const wx = (octSample(0, 0.0, bx * 3.0, by * 3.0) - 0.5) * WARP_AMOUNT;
        const wy = (octSample(0, OCTAVES[0].w, bx * 3.0 + 7.7, by * 3.0 + 3.1) - 0.5) * WARP_AMOUNT;
        var sum: f32 = 0;
        for (OCTAVES, 0..) |o, k| {
            const n = octSample(k, 0.0, (bx + wx) * @as(f32, @floatFromInt(o.w)), (by + wy) * @as(f32, @floatFromInt(o.h)));
            // Ridged from the second octave up. Folding each octave about its
            // midpoint turns a smooth blob into sharp crests, which is what
            // reads as terrain: mountain chains instead of amoeba, and where a
            // valley between two of them reaches sea level it cuts a fjord
            // rather than ending in a bay. The coarse octave stays smooth --
            // ridging it too makes the whole island a fan of spines, and it is
            // the one that decides the landmass shape. Same mean as the smooth
            // octave, so sea level still calibrates against the same range.
            const v = if (k < 2) n else 1.0 - @abs(2.0 * n - 1.0);
            sum += o.amp * v;
        }
        // Sink the field toward the edges so the map still reads as an island
        // without pinning any tile. The old hard sea ring forced the class back
        // one step per tile from the border, and that constant gradient is what
        // drew straight beaches. Folding the falloff into the *height* instead
        // means the coast sits on a noise iso-contour, so it wiggles.
        const h = sum - fall;
        height[y * MAP_W + x] = h;
        peak = @max(peak, h);
    };
    // Scale against this world's own tallest peak. The raw field tops out
    // wherever the lattice rolled, so fixed thresholds would leave snow and
    // rock unreachable on a flat roll and swallow the map on a spiky one.
    if (peak > 0) {
        for (&height) |*h| h.* /= peak;
    }
}

/// How much to sink the field near the edges, 0 in the middle and past 1 in the
/// corners. Radial rather than a distance-to-nearest-edge ramp: that would sink
/// the map to a rounded rectangle, and the coast would trace the rounded
/// rectangle. A radial falloff puts the shore on a noise iso-contour instead.
/// Where the land is allowed to be, as a bias of roughly +/-0.35.
///
/// This is what stops the map being one oval. A falloff based on distance from
/// the centre is a circle whatever noise is piled on it, because every
/// contour of "distance from a point" is a circle -- so the island is always a
/// perturbed disc, and the detail octaves only roughen its rim. A land mask at
/// a much lower frequency than any octave instead decides *where* the land is,
/// so the coastline follows the mask's contour: big lobes, real bays, and
/// secondaries that get cut off as islands. Signed, so it can both add land
/// where the field was thin and take it away where the field was fat.
fn landMask(bx: f32, by: f32) f32 {
    // Octave 1 is a 13x8 lattice; sampling it across bx*2 puts barely two cells
    // over the whole map, which is the point -- this is shape, not detail.
    return (octSample(1, 0.0, bx * 2.0 + 31.7, by * 2.0 + 17.3) - 0.5) * 1.05;
}

fn edgeFall(bx: f32, by: f32) f32 {
    const nx = (bx - 0.5) * 2.0;
    const ny = (by - 0.5) * 2.0;
    // 0 at the centre, ~1 at the middle of an edge, ~1.25 in the corners
    const r = @sqrt(nx * nx + ny * ny);
    // Push the radius around with the coarse octave, otherwise the falloff is a
    // clean ellipse and the shore traces that ellipse -- the same problem as
    // the sea ring, one shape up. Perturbing the radius puts the coast back on
    // a noise iso-contour, so it bays and points instead of arcing.
    const wobble = (octSample(0, 19.0, bx * 2.0 + 4.3, by * 2.0 + 8.1) - 0.5) * 0.75;
    const t = @min(@max((r + wobble - SHORE_START) / (1.0 - SHORE_START), 0.0), 1.0);
    return t * t * (3 - 2 * t) * 1.7;
}

/// Where the shore starts, as a fraction of the half-diagonal.
const SHORE_START: f32 = 0.86;

fn noiseVal(x: u32, y: u32, s: u32) f32 {
    return @as(f32, @floatFromInt(hash(x, y, s ^ height_salt) & 0xFFFF)) / 65535.0;
}

/// Value noise at fractional lattice coords, wrapping instead of clamping.
///
/// `skip` picks a different window of the same wrapping octave so two
/// independent fields can be read out of one lattice. Wrapping is what makes
/// the warp safe: a clamped sample goes flat where the warp pushes it off the
/// lattice, and a flat field near the map edge is precisely the straight
/// shoreline this is here to remove.
fn octSample(k: usize, skip: f32, fx: f32, fy: f32) f32 {
    const o = OCTAVES[k];
    const fw: f32 = @floatFromInt(o.w);
    const fh: f32 = @floatFromInt(o.h);
    const gx = fx + skip;
    const gy = fy + skip;
    const ix = @floor(gx);
    const iy = @floor(gy);
    const x0: usize = @intFromFloat(@mod(ix, fw));
    const y0: usize = @intFromFloat(@mod(iy, fh));
    const x1 = (x0 + 1) % o.w;
    const y1 = (y0 + 1) % o.h;
    const tx = gx - ix;
    const ty = gy - iy;
    // smoothstep fade, so the field has no lattice creases -- a straight lerp
    // would band along every lattice line
    const sx = tx * tx * (3 - 2 * tx);
    const sy = ty * ty * (3 - 2 * ty);
    const base = OCT_OFF[k];
    return lerp(
        lerp(oct_pool[base + y0 * o.w + x0], oct_pool[base + y0 * o.w + x1], sx),
        lerp(oct_pool[base + y1 * o.w + x0], oct_pool[base + y1 * o.w + x1], sx),
        sy,
    );
}

/// The class a cell would ideally be, from its height. These band edges are
/// the real knobs of the world: they set how much of the map is ocean, how
/// wide the beaches are, and how much of the highlands is snow.
///
/// Land is banded as a *fraction of the way from the shore to the highest
/// point in this world*, not as a fixed offset from `sea`. A fixed offset only
/// works while the offset happens to fit: the field is normalised so its tallest
/// point is 1.0, and `sea` ranges 0.20..0.38, so an edge at `sea + 0.70` landed
/// off the top of the scale on every high-sea world and the top two bands
/// simply never appeared. Fractions keep every band reachable at any sea level,
/// and they scale the whole climb to the land that is actually there.
fn wantClass(h: f32) u8 {
    if (h < sea) return DEEP;
    if (h < sea + 0.015) return SHALLOW;
    if (h < sea + 0.035) return SAND;
    // how far up the land this cell sits, 0 at the shore and 1 at the peak
    const up = (h - sea - 0.035) / @max(1.0 - sea - 0.035, 0.01);
    if (up < 0.13) return GRASS;
    if (up < 0.27) return FOREST;
    if (up < 0.39) return FOREST_DEEP;
    if (up < 0.51) return ROCK;
    if (up < 0.65) return ROCK_HIGH;
    if (up < 0.78) return PEAK;
    return SNOW;
}

var masks: [CELLS]u16 = @splat(ALL_TILES); // tiles still allowed per cell
var world: [CELLS]u8 = @splat(DEEP); // the chosen tile, valid once solved
var queued: [CELLS]bool = @splat(false);
var stack: [CELLS]u16 = undefined;
var solved: bool = false;
/// `zig build -Dseed=N` pins this, so `make seeds` can render a spread of
/// worlds without editing the source between builds.
var seed: u32 = cfg.seed orelse 0xC0FFEE;
var rng: u32 = 0xC0FFEE;
var retries: u32 = 0;
var frame: i32 = 0;
var cam_x: i32 = 0;
var cam_y: i32 = 0;
/// X swaps the scrolling view for the whole world at one pixel per tile.
/// `zig build -Dmap_view=1` starts there instead, so `make overview` can render
/// the whole map from the command line with no TTY to press X in.
var zoomed_out: bool = cfg.map_view;
/// The mouse API reports held, not just-pressed, so every mouse button needs its
/// own previous-frame state to find the edge on.
var mouse_was_down: bool = false;
var mouse_right_was_down: bool = false;

/// Top-left of the 1:1 overview, centred in the area above the HUD.
const MAP_X: i32 = (vex.WIDTH - @as(i32, @intCast(MAP_W))) / 2;
const MAP_Y: i32 = (HUD_Y - @as(i32, @intCast(MAP_H))) / 2;

/// The whole map at one pixel per tile, with the scrolling viewport outlined so
/// you can see where you are and pick a spot to go back to.
fn drawOverview() void {
    vex.cls(C.ui_bg);
    for (0..MAP_H) |y| {
        for (0..MAP_W) |x| {
            vex.pset(MAP_X + @as(i32, @intCast(x)), MAP_Y + @as(i32, @intCast(y)), TILES[world[y * MAP_W + x]].map);
        }
    }
    // the viewport, clamped to the map: the camera can sit low enough that the
    // 11-row window overhangs the last row, and an outline drawn off the edge
    // would just be cut off mid-line
    const vx = @divTrunc(cam_x, @as(i32, @intCast(T)));
    const vy = @divTrunc(cam_y, @as(i32, @intCast(T)));
    const vw = @min(VIEW_W, @as(i32, @intCast(MAP_W)) - vx);
    const vh = @min(VIEW_H, @as(i32, @intCast(MAP_H)) - vy);
    vex.rectb(MAP_X + vx, MAP_Y + vy, vw, vh, C.ui_bright);

    vex.rect(0, HUD_Y, vex.WIDTH, vex.HEIGHT - HUD_Y, C.ui_bg);
    vex.text(say("SEED {X}  MAP {d}x{d}", .{ seed, MAP_W, MAP_H }), 4, HUD_Y + 2, C.ui_text);
    vex.text(HINT_MAP, 4, HUD_Y + 11, C.ui_dim);
}

// -- entropy buckets --------------------------------------------------------
// WFC collapses the cell with the *fewest* options left, which is what keeps
// contradictions rare. Finding that cell by rescanning the whole map made the
// whole solve quadratic -- N collapses, each scanning N cells -- and that is
// what capped the map size: 12k cells took ~430ms, and the trend put 51k cells
// somewhere past 7 seconds.
//
// Entropy here is just a popcount of a u16 mask, so it is bounded to
// TILE_COUNT values. Keeping the undecided cells in one list per entropy makes
// "the fewest options" a walk down nine heads instead of a scan, and the solve
// becomes linear in cells. Each cell sits in exactly one list, as an intrusive
// doubly-linked node, so narrowing a cell moves it between lists in O(1) rather
// than leaving a stale duplicate behind in a bucket that is never drained.
//
// Doubly linked because a cell is usually removed from the *middle* of a list
// (it narrowed while sitting in a list of its old entropy) and a singly linked
// list cannot unlink without the predecessor.

const NO_CELL: u16 = 0xFFFF; // list terminator; also the "not in a list" marker
const MAX_ENTROPY: usize = TILE_COUNT;

var bucket_head: [MAX_ENTROPY + 1]u16 = @splat(NO_CELL);
var bucket_next: [CELLS]u16 = @splat(NO_CELL);
var bucket_prev: [CELLS]u16 = @splat(NO_CELL);
/// Which entropy list a cell is on, or NO_CELL if it is decided/not queued.
var bucket_of: [CELLS]u8 = @splat(@as(u8, 0xFF));

/// Drop every cell from the lists. Needed at the start of a world: linking cells
/// straight back in would splice them onto the *previous* world's list head and
/// chain the two together, so walking a list would run off the end.
fn bucketsClear() void {
    for (&bucket_head) |*h| h.* = NO_CELL;
    for (&bucket_of) |*b| b.* = 0xFF;
    for (&bucket_next) |*n| n.* = NO_CELL;
    for (&bucket_prev) |*p| p.* = NO_CELL;
}

fn bucketLink(i: usize, b: usize) void {
    const u: u16 = @intCast(i);
    const ub: u16 = @intCast(b);
    bucket_prev[u] = NO_CELL;
    bucket_next[u] = bucket_head[ub];
    if (bucket_head[ub] != NO_CELL) bucket_prev[bucket_head[ub]] = u;
    bucket_head[ub] = u;
    bucket_of[u] = @intCast(b);
}

fn bucketUnlink(i: usize) void {
    const u: u16 = @intCast(i);
    const b = bucket_of[u];
    if (b == 0xFF) return;
    const p = bucket_prev[u];
    const n = bucket_next[u];
    if (p == NO_CELL) {
        bucket_head[b] = n;
    } else {
        bucket_next[p] = n;
    }
    if (n != NO_CELL) bucket_prev[n] = p;
    bucket_prev[u] = NO_CELL;
    bucket_next[u] = NO_CELL;
    bucket_of[u] = 0xFF;
}

/// Put `i` in the list matching its current options. Decided cells leave the
/// lists entirely, which is what makes "every list empty" mean "map solved".
fn bucketRequeue(i: usize) void {
    const n: u8 = @intCast(@popCount(masks[i]));
    if (n <= 1) {
        bucketUnlink(i);
        return;
    }
    if (bucket_of[i] == n) return; // already in the right place
    bucketUnlink(i);
    bucketLink(i, n);
}

/// The cell with the fewest options left, or null once every cell is decided.
/// Ties come out of the list order, which is the order the cells were narrowed
/// in -- that walks the constraint frontier outward, which is a decent
/// substitute for picking uniformly among equals, and uniform would cost a scan
/// all over again.
fn pickCell() ?usize {
    var b: usize = 2;
    while (b <= MAX_ENTROPY) : (b += 1) {
        while (bucket_head[b] != NO_CELL) {
            const i: usize = bucket_head[b];
            if (bucket_of[i] == b) return i;
            bucketUnlink(i); // stale: the cell has narrowed since
        }
    }
    return null;
}

fn rnd() u32 {
    rng ^= rng << 13;
    rng ^= rng >> 17;
    rng ^= rng << 5;
    if (rng == 0) rng = 0xDEADBEEF;
    return rng;
}

/// Push the consequences of `start`'s options out to its neighbours.
/// Returns false on a contradiction, which means this seed is a dead end.
fn propagate(start: usize) bool {
    var sp: usize = 0;
    stack[sp] = @intCast(start);
    queued[start] = true;
    sp += 1;
    while (sp > 0) {
        sp -= 1;
        const c: usize = stack[sp];
        queued[c] = false;
        const cx = c % MAP_W;
        const cy = c / MAP_W;
        for (0..4) |d| {
            const nx = @as(i32, @intCast(cx)) + DX[d];
            const ny = @as(i32, @intCast(cy)) + DY[d];
            if (nx < 0 or ny < 0 or nx >= MAP_W or ny >= MAP_H) continue;
            const n: usize = @as(usize, @intCast(ny)) * MAP_W + @as(usize, @intCast(nx));

            var allow: u16 = 0;
            var m = masks[c];
            while (m != 0) {
                const t: usize = @ctz(m);
                m &= m - 1;
                allow |= ALLOWED[OPP[d]][t];
            }
            const next = masks[n] & allow;
            if (next == 0) return false;
            if (next != masks[n]) {
                masks[n] = next;
                // the cell's options changed, so it belongs in a different
                // entropy list than the one it was on
                bucketRequeue(n);
                if (!queued[n]) {
                    queued[n] = true;
                    stack[sp] = @intCast(n);
                    sp += 1;
                }
            }
        }
    }
    return true;
}

/// A tile from `mask` for cell `i`, aimed at the elevation `height[i]` wants.
/// The closest class always wins; where two tiles share that class (plains and
/// ruins are both class 3) the weight decides, so ruins stay rare. Picking on
/// weight alone gives a map of static, not a world.
fn pickTile(i: usize, mask: u16) u8 {
    const want = wantClass(height[i]);
    var best_d: u8 = 255;
    var pool: u16 = 0;
    for (0..TILE_COUNT) |t| {
        if (mask & (@as(u16, 1) << @intCast(t)) == 0) continue;
        const d = @abs(@as(i32, TILES[t].cls) - @as(i32, want));
        if (d < best_d) {
            best_d = @intCast(d);
            pool = @as(u16, 1) << @intCast(t);
        } else if (d == best_d) {
            pool |= @as(u16, 1) << @intCast(t);
        }
    }
    var total: u32 = 0;
    for (0..TILE_COUNT) |t| {
        if (pool & (@as(u16, 1) << @intCast(t)) != 0) total += TILES[t].weight;
    }
    var r = rnd() % total;
    for (0..TILE_COUNT) |t| {
        if (pool & (@as(u16, 1) << @intCast(t)) == 0) continue;
        if (r < TILES[t].weight) return @intCast(t);
        r -= TILES[t].weight;
    }
    return @intCast(@ctz(pool));
}

/// Start a new world. Returns non-zero if a seed ever fails to pin the sea
/// ring, which would be a bug in the tile rules rather than a dead end.
fn reset(s: u32) u32 {
    seed = s;
    rng = s | 1;
    height_salt = s;
    buildHeight(s);
    // 0.34..0.52: some worlds are mostly archipelago, some mostly continent
    sea = 0.20 + @as(f32, @floatFromInt(rnd() % 19)) * 0.01;
    for (&masks) |*m| m.* = ALL_TILES;
    // Every cell starts wide open, so start them all in the widest list.
    bucketsClear();
    for (0..CELLS) |i| bucketLink(i, MAX_ENTROPY);
    // No sea ring. One used to frame the map as an island, but pinning the
    // border to open sea fights the field: the terrain wants land right up to
    // the edge, and |cls delta| <= 1 only lets the class climb one step per
    // tile, so the ring dragged a 4-tile water gradient all the way round the
    // map. That gradient is what drew a dead-straight beach parallel to every
    // edge. The map edge is a viewport edge, not a coastline, so terrain is
    // free to run off it.
    solved = false;
    return 0;
}

/// Collapse up to `budget` cells, or until the map is decided / a dead end
/// turns up. Returns the seed of a finished world, 0 if there is still work.
fn solve(budget: usize) u32 {
    var n = budget;
    while (n > 0) {
        n -= 1;
        const c = pickCell() orelse {
            for (0..CELLS) |i| world[i] = @intCast(@ctz(masks[i]));
            solved = true;
            return seed;
        };
        masks[c] = @as(u16, 1) << @intCast(pickTile(c, masks[c]));
        bucketRequeue(c); // decided: off the lists
        if (!propagate(c)) {
            // Dead end: a seed always dies the same way, so re-roll from it.
            retries += 1;
            return reset(seed +% retries *% 0x9E3779B9);
        }
    }
    return 0;
}

// -- draw -------------------------------------------------------------------

// The `:0` gives the buffer a sentinel slot, and `say` writes the NUL itself:
// std.fmt.bufPrint returns only the bytes it formatted, so slicing
// `hud[0..s.len :0]` without this would hand the host a "string" that still
// ends in the *previous* frame's text (BEACH after SHALLOWS reads BEACHSNDS).
var hud: [96:0]u8 = undefined;

fn say(comptime f: []const u8, args: anytype) [*:0]const u8 {
    const s = std.fmt.bufPrint(&hud, f, args) catch unreachable;
    hud[s.len] = 0;
    return hud[0..s.len :0];
}

fn draw() void {
    if (!solved) {
        vex.cls(C.ui_bg);
        var done: usize = 0;
        for (0..CELLS) |i| done += @intFromBool(@popCount(masks[i]) == 1);
        vex.text("COLLAPSING THE WORLD", 8, 8, C.ui_text);
        vex.rect(8, 20, 120, 4, C.ui_dim);
        vex.rect(8, 20, 120 * @divTrunc(@as(i32, @intCast(done)), @as(i32, @intCast(CELLS))), 4, C.ui_fill);
        vex.text(say("SEED {X}", .{seed}), 8, 32, C.ui_dim);
        return;
    }

    if (zoomed_out) {
        drawOverview();
        return;
    }

    const t_i: i32 = @intCast(T);
    // One tile more than the viewport needs, because the camera pans in whole
    // pixels: at cam % 16 != 0 the visible area ends part-way into an extra
    // column/row, and drawing only VIEW_W/VIEW_H leaves its last pixel line
    // showing whatever was there before. Tiles past the map edge are off-screen
    // anyway (the camera is clamped), so they are simply skipped.
    for (0..@as(usize, @intCast(VIEW_H + 1))) |r| for (0..@as(usize, @intCast(VIEW_W + 1))) |c| {
        const tx = @divTrunc(cam_x, t_i) + @as(i32, @intCast(c));
        const ty = @divTrunc(cam_y, t_i) + @as(i32, @intCast(r));
        if (tx >= MAP_W or ty >= MAP_H) continue;
        const t = world[@as(usize, @intCast(ty)) * MAP_W + @as(usize, @intCast(tx))];
        // only the sea animates; the alternate frame is a phase shift of the
        // same noise, so the water rolls instead of strobing
        const phase: usize = if (t <= SHALLOW) @intCast((tx + ty + (frame >> 4)) & 1) else 0;
        // variant keyed off the map position, so it is stable as the camera
        // scrolls -- hashing the screen position would make the ground crawl
        const v: usize = @intCast(hash(@bitCast(tx), @bitCast(ty), 0x5A5A) % VARIANTS);
        const sx = tx * t_i - cam_x;
        const sy = ty * t_i - cam_y;
        vex.blit(&TILES[t].art[v][phase], sx, sy, t_i, t_i, -1);
        // Blend in each east/south neighbour that is a different terrain, over
        // just the half of this tile facing it. Only these two sides draw, so
        // the tile earlier in row-major order owns each seam and the blend is
        // one ramp instead of two overlapping.
        //
        // Asymmetric in ruins, deliberately. As a band *source* ruins stays
        // excluded, because its art is walls and roof: blending it outward
        // scatters roof pixels across the grass next door. As a band *target* it
        // has to be allowed, because otherwise a ruin owns its own seams and
        // declines to draw them, leaving a hard cut where every other terrain
        // boundary is dithered -- a ruin on a beach read as a rectangle pasted
        // onto the map, with a crisp vertical line down one side. Receiving a
        // band is safe in the one direction that matters: the neighbour's
        // terrain feathers into the ruin's edge, and no roof leaves the tile.
        for (BAND_DIRS) |d| {
            const nx = tx + DX[d];
            const ny = ty + DY[d];
            if (nx < 0 or ny < 0 or nx >= MAP_W or ny >= MAP_H) continue;
            const nb = world[@as(usize, @intCast(ny)) * MAP_W + @as(usize, @intCast(nx))];
            if (nb == t or !bandsWith(nb)) continue;
            // the band's blend texture has to be the variant the neighbour
            // actually draws, or every seam mismatches and the squares show
            const nv: usize = @intCast(hash(@bitCast(nx), @bitCast(ny), 0x5A5A) % VARIANTS);
            vex.blit(&BANDS[nb][dirSlot(d)][nv], sx, sy, t_i, t_i, 0); // 0 = transparent
        }
    };

    // The mouse can sit below the last map row (over the HUD, or in the sliver
    // The console reports a pointer position even when the window does not have
    // focus, and that position is not a screen coordinate -- it can be negative,
    // or past the far edge. Feed it to the map only when it really is on screen:
    // an out-of-range one extrapolates into a scroll (sending the camera off to
    // a corner the moment the window opens) and reads the map out of bounds.
    // Clamped rather than discarded, so the HUD still shows a valid tile.
    const mx = std.math.clamp(vex.mx(), 0, vex.WIDTH - 1);
    const my = std.math.clamp(vex.my(), 0, vex.HEIGHT - 1);
    const hx = @divTrunc(cam_x + mx, t_i);
    const hy = @min(@divTrunc(cam_y + my, t_i), @as(i32, @intCast(MAP_H)) - 1);
    const hover: u8 = world[@as(usize, @intCast(hy)) * MAP_W + @as(usize, @intCast(hx))];
    // Outline the pointed-at tile only while the button is held and the cursor
    // is over the map. Held, because edge scrolling moves the world under a
    // stationary cursor, so the tile under it changes every frame the camera
    // creeps and the outline strobes. Pressed-to-inspect, the highlight is
    // something you go and get rather than something that follows you around.
    //
    // Two rings. The inner one is the tile's own primary tone, which ties the
    // marker to the terrain rather than sitting on top of it -- but an outline
    // in a tile's own colour is by definition near-zero contrast against that
    // tile, and vanished outright on the plains, which are one flat tone. The
    // outer ring is a pixel beyond the tile, so it is drawn on the *neighbours*
    // and keeps a visible boundary whatever they happen to be.
    if (my < HUD_Y and vex.mdown(vex.MOUSE_LEFT)) {
        vex.rectb(hx * t_i - cam_x - 1, hy * t_i - cam_y - 1, t_i + 2, t_i + 2, C.ui_bright);
        vex.rectb(hx * t_i - cam_x, hy * t_i - cam_y, t_i, t_i, TILES[hover].map);
    }

    vex.rect(0, HUD_Y, vex.WIDTH, vex.HEIGHT - HUD_Y, C.ui_bg);
    vex.text(say("SEED {X}  {d},{d}  {s}", .{ seed, hx, hy, TILES[hover].name }), 4, HUD_Y + 2, C.ui_text);
    vex.text(HINT_SCROLL, 4, HUD_Y + 11, C.ui_dim);
}

/// Both HUD hint lines, kept as consts so the fit check below sees them and the
/// two views cannot drift into wording that no longer matches the bindings.
/// Sized to the 8x8 console font: 39 characters fit between the margins, and the
/// old scrolling hint was 55, so "RMB MAP   Z NEW" was drawn off-screen and
/// never rendered. Clipped text does not look clipped -- the line just ends.
const HINT_SCROLL = "ARROWS/LMB SCROLL   X/RMB MAP   Z NEW";
const HINT_MAP = "CLICK MOVE BOX   X/RMB WORLD";

/// 8x8 glyphs, per the console font.
const CHAR_W: i32 = 8;
const HUD_MARGIN: i32 = 4;

/// Map tile under a click in the 1:1 overview, or null if the click landed off
/// the map -- on the frame, or on the HUD. Null matters: a click just past the
/// edge would otherwise recentre on a tile far off the island, and the camera
/// would jump somewhere the player never pointed at.
fn overviewTileAt(mx: i32, my: i32) ?struct { x: i32, y: i32 } {
    const x = mx - MAP_X;
    const y = my - MAP_Y;
    if (x < 0 or y < 0) return null;
    if (x >= @as(i32, @intCast(MAP_W)) or y >= @as(i32, @intCast(MAP_H))) return null;
    return .{ .x = x, .y = y };
}

fn input() void {
    if (vex.pressed(vex.X)) zoomed_out = !zoomed_out;
    const speed: i32 = 2;
    if (vex.down(vex.LEFT)) cam_x -= speed;
    if (vex.down(vex.RIGHT)) cam_x += speed;
    if (vex.down(vex.UP)) cam_y -= speed;
    if (vex.down(vex.DOWN)) cam_y += speed;

    // Read the button once: edge scrolling and the overview click both want it,
    // and two reads of a "held" state is two chances to disagree.
    const held = vex.mdown(vex.MOUSE_LEFT);
    const clicked = justPressed(held, mouse_was_down);
    mouse_was_down = held;

    // Right button toggles the overview as well, for anyone who never finds X.
    //
    // Rising edge, and that is not optional: the mouse API has no "just
    // pressed", only held, so testing the button itself would flip the view
    // every frame it is down and land wherever an odd number of frames left it.
    const right = vex.mdown(vex.MOUSE_RIGHT);
    if (justPressed(right, mouse_right_was_down)) zoomed_out = !zoomed_out;
    mouse_right_was_down = right;

    // Edge scrolling, while the button is held -- see edgeScrollAllowed for why
    // each of the three conditions is there. Measured over the whole screen, HUD
    // included: measuring against the map area instead leaves the bottom strip
    // dead, and the lowest place you can scroll from is then the last map row
    // rather than the bottom of the screen, which reads as being off by one.
    if (edgeScrollAllowed(zoomed_out, held, mouseOnScreen())) {
        cam_x += edgeScroll(vex.mx(), vex.WIDTH);
        cam_y += edgeScroll(vex.my(), vex.HEIGHT);
    }

    // Clicking the overview moves the viewport box there, the same job the arrow
    // keys do, so the map is usable without hunting for a key that matches the
    // direction you want. The mouse API has no "just pressed", only held, so the
    // edge is detected above.
    if (zoomed_out and clicked and mouseOnScreen()) {
        if (overviewTileAt(vex.mx(), vex.my())) |t| {
            const ti: i32 = @intCast(T);
            cam_x = (t.x - @divTrunc(VIEW_W, 2)) * ti;
            cam_y = (t.y - @divTrunc(VIEW_H, 2)) * ti;
        }
    }

    cam_x = std.math.clamp(cam_x, 0, MAX_CAM_X);
    cam_y = std.math.clamp(cam_y, 0, MAX_CAM_Y);
    if (vex.pressed(vex.Z)) {
        retries = 0;
        _ = reset(rnd());
        cam_x = MAX_CAM_X / 2;
        cam_y = MAX_CAM_Y / 2;
    }
}

/// How close to an edge the mouse has to be before the camera scrolls, and how
/// fast it goes at the very edge (px/frame).
const EDGE: i32 = 24;
const EDGE_SPEED: i32 = 4;

/// Is the pointer actually within the screen? The console reports a position
/// whether or not the window has focus, and that position is not a screen
/// coordinate when the pointer is elsewhere -- it can be negative or past the
/// far edge. Anything derived from it has to be gated on this, or it will
/// extrapolate: as a scroll that walks the camera into a corner, as a tile index
/// that reads the map out of bounds.
fn mouseOnScreen() bool {
    return vex.mx() >= 0 and vex.mx() < vex.WIDTH and
        vex.my() >= 0 and vex.my() < vex.HEIGHT;
}

/// The frame a held button goes down, given its state now and last frame.
///
/// The keyboard has `pressed()` for this but the mouse does not -- `mbtn` is
/// held only, so a one-shot mouse action has to find the edge itself. Without
/// this, a toggle bound to the button fires every frame it is down and the view
/// flips as fast as the frame rate.
fn justPressed(held: bool, was_down: bool) bool {
    return held and !was_down;
}

/// Whether the mouse should move the camera this frame. Split out from input()
/// so the rule is one named thing rather than a condition buried in a block of
/// camera maths -- the button is the part that is easy to drop, and a dropped
/// `held` is invisible: the cart still runs, it just slides away on its own as
/// soon as the pointer rests near an edge.
///
/// Split three ways because all three are load-bearing. `zoomed_out`: the whole
/// map is already on screen, so there is nowhere to scroll to. `held`: a
/// pointer resting near an edge is not a request to move, and the cart boots
/// wherever the pointer happens to be -- with the button ignored, a pointer left
/// in the top left walked the camera off the map before anyone had touched
/// anything. `on_screen`: an unfocused window still reports a position that is
/// not a screen coordinate, and a negative one extrapolates into a scroll.
fn edgeScrollAllowed(zoomed: bool, held: bool, on_screen: bool) bool {
    return !zoomed and held and on_screen;
}

/// Scroll speed for a cursor `m` px along an axis of `extent` px: zero away
/// from the edges, ramping to +/-EDGE_SPEED pinned to them. Ramped rather than
/// constant so nudging the mouse to an edge drifts gently instead of lurching.
///
/// Signed, and that is the whole point: the speed has to point *away* from the
/// edge the cursor is against. Returning a bare magnitude and letting the
/// caller add it means both edges scroll the same direction, and the camera
/// can then only ever travel one way along each axis -- which is a silent,
/// very confusing half-broken control rather than an obvious failure.
///
/// `m` must be within `[0, extent-1]`, which is what the mouse reads over the
/// full screen, so nothing extrapolates past the far edge. The one axis that
/// was not a clean match was y: the HUD strip sits below the map, and measuring
/// against the map area alone would have pushed `m` past `extent - 1`.
fn edgeScroll(m: i32, extent: i32) i32 {
    // Magnitude ramps from 0 at the inner edge of the margin to EDGE_SPEED at
    // the screen edge -- so it is measured from the margin inward on both
    // sides. Measuring from the screen edge instead makes the cursor pinned
    // against the screen get *zero* speed, which reads as the control not
    // working at all.
    if (m < EDGE) return -@divTrunc(EDGE_SPEED * (EDGE - m), EDGE);
    if (m > extent - 1 - EDGE) return @divTrunc(EDGE_SPEED * (m - (extent - 1 - EDGE)), EDGE);
    return 0;
}

export fn boot() void {
    vex.title("vex-world");
    for (JONK16, 0..) |rgb, i| vex.pal(@intCast(i), @bitCast(rgb));
    _ = reset(seed);
    cam_x = MAX_CAM_X / 2;
    cam_y = MAX_CAM_Y / 2;
}

export fn update() void {
    frame += 1;
    input();
    if (!solved) _ = solve(GENERATE_PER_FRAME);
    draw();
}

// -- checks -----------------------------------------------------------------
// The `env` host imports only exist inside the console, so run these against
// src/env.zig, which stands in for that module (or just `make test`):
//   zig build-lib -dynamic --name env src/env.zig -lc && \
//   LD_LIBRARY_PATH=. zig test -target x86_64-linux-gnu --dep vex \
//     -Mroot=src/cart.zig -Mvex=<sdk>/vex.zig -L. -lenv

test "a solved world obeys every adjacency rule" {
    for (0..4) |trial| {
        try std.testing.expectEqual(@as(u32, 0), reset(0xC0FFEE +% @as(u32, @intCast(trial))));
        var guard: usize = 0;
        while (!solved and guard < 100) : (guard += 1) _ = solve(CELLS);
        try std.testing.expect(solved);
        for (0..MAP_H) |y| for (0..MAP_W) |x| {
            const i = y * MAP_W + x;
            // every cell decided
            try std.testing.expectEqual(@as(u16, 1), @as(u16, @intCast(@popCount(masks[i]))));
            if (x + 1 < MAP_W) try std.testing.expect(adjacent(world[i], world[i + 1]));
            if (y + 1 < MAP_H) try std.testing.expect(adjacent(world[i], world[i + MAP_W]));
        };
    }
}

test "the same seed always collapses to the same world" {
    var first: [CELLS]u8 = undefined;
    for (0..2) |pass| {
        _ = reset(0x1234_5678);
        var guard: usize = 0;
        while (!solved and guard < 100) : (guard += 1) _ = solve(CELLS);
        try std.testing.expect(solved);
        if (pass == 0) first = world else try std.testing.expectEqualSlices(u8, &first, &world);
    }
}

test "the adjacency table is symmetric and never empty" {
    for (0..4) |d| for (0..TILE_COUNT) |a| for (0..TILE_COUNT) |b| {
        if (ALLOWED[d][a] & (@as(u16, 1) << @intCast(b)) == 0) continue;
        try std.testing.expect(ALLOWED[OPP[d]][b] & (@as(u16, 1) << @intCast(a)) != 0);
    };
    for (0..4) |d| for (0..TILE_COUNT) |a| {
        try std.testing.expect(ALLOWED[d][a] != 0);
    };
}

test "propagation only ever removes options, never adds them" {
    _ = reset(0xABCD);
    const before = masks;
    _ = solve(1);
    var narrowed: usize = 0;
    for (0..CELLS) |i| {
        try std.testing.expect(masks[i] & before[i] == masks[i]);
        if (masks[i] != before[i]) narrowed += 1;
    }
    // collapsing one cell out of 1536 has to constrain its neighbourhood,
    // otherwise propagation is not wired up at all
    try std.testing.expect(narrowed > 0);
}

test "the picked tile is allowed and as close to the aim as possible" {
    _ = reset(0x99);
    for (0..CELLS) |i| {
        // an unrestricted cell: the aim alone decides the class
        try std.testing.expectEqual(TILES[pickTile(i, ALL_TILES)].cls, wantClass(height[i]));

        // a real cell: the pick must come out of the options propagation left
        const m = masks[i];
        const t = pickTile(i, m);
        try std.testing.expect(m & (@as(u16, 1) << @intCast(t)) != 0);

        // and if the aim's class is still on the table, that is what we get
        var reachable: u8 = 255;
        for (0..TILE_COUNT) |k| {
            if (m & (@as(u16, 1) << @intCast(k)) != 0) {
                reachable = @min(reachable, TILES[k].cls);
            }
        }
        const d_want = @abs(@as(i32, wantClass(height[i])) - @as(i32, reachable));
        const d_got = @abs(@as(i32, TILES[t].cls) - @as(i32, wantClass(height[i])));
        try std.testing.expect(d_got <= d_want);
    }
}

test "the drawn tile grid covers the whole viewport at every camera offset" {
    const t: i32 = @intCast(T);
    const mw: i32 = @intCast(MAP_W);
    const mh: i32 = @intCast(MAP_H);
    // The camera scrolls in pixels, so it sits at every offset 0..15 inside a
    // tile. At a non-zero offset the viewport ends part-way into an extra
    // column/row, and a grid of exactly VIEW_W x VIEW_H tiles would leave the
    // final pixel column and row showing whatever was there before. Walk every
    // reachable camera position and check the tiles actually blitted -- the
    // in-bounds ones, since the rest are skipped -- span the full map area.
    var cam: i32 = 0;
    while (cam <= MAX_CAM_X) : (cam += 1) {
        var row: i32 = 0;
        while (row <= MAX_CAM_Y) : (row += 1) {
            const x0 = @divTrunc(cam, t);
            const y0 = @divTrunc(row, t);
            // draw() walks VIEW_W+1 / VIEW_H+1 tiles but skips any past the
            // map, so the covered strip ends at the last in-bounds tile
            const x1 = @min(x0 + VIEW_W + 1, mw);
            const y1 = @min(y0 + VIEW_H + 1, mh);
            const left = x0 * t - cam;
            const top = y0 * t - row;
            const right = x1 * t - cam;
            const bottom = y1 * t - row;
            try std.testing.expect(left <= 0);
            try std.testing.expect(top <= 0);
            try std.testing.expect(right >= vex.WIDTH);
            try std.testing.expect(bottom >= HUD_Y);
        }
    }
}

test "say() NUL-terminates, so a short string cannot inherit the previous one" {
    // the failure mode: a long name is formatted, then a shorter one. Without
    // an explicit NUL the host keeps reading into the long string's tail, so
    // "BEACH" renders as "BEACHSNDS" after "SHALLOWS".
    const long = say("SEED {X}  {d},{d}  {s}", .{ @as(u32, 0xDEADBEEF), 47, 31, "SHALLOWS" });
    try std.testing.expectEqualStrings("SEED DEADBEEF  47,31  SHALLOWS", std.mem.span(long));

    const short = say("SEED {X}  {d},{d}  {s}", .{ @as(u32, 0xDEADBEEF), 47, 31, "BEACH" });
    try std.testing.expectEqualStrings("SEED DEADBEEF  47,31  BEACH", std.mem.span(short));
    // the byte the host stops at must really be NUL
    try std.testing.expectEqual(@as(u8, 0), short[std.mem.span(short).len]);
    // and it must not have been left over from the longer string
    try std.testing.expect(!std.mem.endsWith(u8, std.mem.span(short), "SNDS"));

    // every tile name, both ways round, is NUL-terminated on its own
    for (0..TILE_COUNT) |t| {
        for (0..TILE_COUNT) |u| {
            const s = say("{s}", .{TILES[u].name});
            try std.testing.expectEqual(@as(u8, 0), s[TILES[u].name.len]);
            try std.testing.expectEqualStrings(TILES[u].name, std.mem.span(s));
            if (TILES[t].name.len > TILES[u].name.len) {
                // force a longer neighbour right before the short one
                const filler = say("{s}", .{TILES[t].name});
                try std.testing.expectEqual(@as(u8, 0), filler[TILES[t].name.len]);
            }
        }
    }
}

test "both water tiles ride one wave, and the wave tiles seamlessly" {
    // The sea animates by folding the tile's map position into `phase`, so the
    // crest has to look the same coming out of every tile. That only happens
    // when the period divides the tile size -- the original bug used a period
    // of 5 against a tile of 16, which shifted the wave in every tile and tore
    // the water along the grid.
    try std.testing.expectEqual(@as(usize, 0), T % CREST_PERIOD);

    // The two water tiles may differ in colour, never in *where* their wave
    // is: DEEP puts its crest in 9 and SHALLOWS in 10 and nothing else, so the
    // set of crest pixels has to match exactly -- in every variant and both
    // frames, since a DEEP tile can sit next to a SHALLOWS one that drew a
    // different variant.
    for (0..VARIANTS) |v| for (0..2) |ph| for (0..NP) |i| {
        const in_deep = TILES[DEEP].art[v][ph][i] == DEEP_CREST;
        const in_shallow = TILES[SHALLOW].art[v][ph][i] == SHALLOW_CREST;
        try std.testing.expectEqual(in_deep, in_shallow);
    };

    // and there has to be a wave in there, or the check above passes on two
    // blank tiles
    var crests: usize = 0;
    for (TILES[DEEP].art[0][0]) |c| crests += @intFromBool(c == DEEP_CREST);
    try std.testing.expect(crests > 0);
}

test "a seam is blended once, and only on the half facing the neighbour" {
    // The bug this pins: bands were drawn on the whole tile *and* on both sides
    // of a seam, so the two overlapped across the entire boundary. A transition
    // came out 16px wide with each terrain visible on the far side of the other
    // -- clearest where two similar terrains meet, e.g. plains into beach and
    // then beach straight back into plains.

    // 1. A band only touches the half of the tile nearest its edge, so the two
    //    halves of a seam together cover one BAND-wide transition, not two.
    for (0..TILE_COUNT) |b| {
        for (BAND_DIRS) |d| {
            var touched: usize = 0;
            for (0..T) |yy| {
                for (0..T) |xx| {
                    if (BANDS[b][dirSlot(d)][0][yy * T + xx] == 0) continue;
                    touched += 1;
                    const along: usize = switch (d) {
                        0 => yy,
                        1 => T - 1 - xx,
                        2 => T - 1 - yy,
                        else => xx,
                    };
                    try std.testing.expect(along < BAND);
                }
            }
            // it has to actually blend, or the check above passes on a blank tile
            try std.testing.expect(touched > 0);
            // and it must never flood the tile
            try std.testing.expect(touched < NP / 2);
        }
    }

    // 2. Every banding kind resolves to a real band, and those bands only ever
    //    contain art colours or the transparent 0 -- if 0 leaked in as art the
    //    blit key would punch holes in the terrain.
    // Ruins are excluded as a band *source* only. It is tempting to read that
    // as "ruins never blend", and the draw loop used to: it gated on
    // `bandsWith(t)` as well, so a ruin also refused to *receive* a band, owned
    // its seams by being earlier in row-major order, and declined to draw them.
    // The result was a hard cut on every ruin boundary while every other
    // terrain boundary dithered -- a building pasted on the map. So the check
    // is on the one direction that is actually unsafe, and the neighbour test
    // in the draw loop is what stops roof leaving a ruin.
    try std.testing.expect(!bandsWith(RUINS));
    // Every *other* kind must be a usable band source, or the exclusion above
    // is not the only one and seams go unblended the same way.
    for (0..TILE_COUNT) |b| {
        if (b == RUINS) continue;
        try std.testing.expect(bandsWith(@intCast(b)));
    }
    for (0..TILE_COUNT) |b| {
        if (!bandsWith(@intCast(b))) continue;
        for (BAND_DIRS) |d| {
            for (BANDS[b][dirSlot(d)][0]) |px| {
                // 0 is the transparency key; anything else must be real art
                try std.testing.expect(px == 0 or (px >= 1 and px <= 15));
            }
        }
    }
}

test "no seam is blended from both sides" {
    // A seam has exactly one owner: the tile earlier in row-major order, which
    // handles it on its east or south side. If a tile also banded its west and
    // north sides, both tiles would fade into each other across the same
    // boundary and the two ramps would fight -- the far terrain would spike to
    // full at the seam and then collapse back to bare inside the near tile.
    // That is why the beach/plains seam read as denser green on the beach side
    // than the plains side, and it applied to every pair, not just that one.
    //
    // BAND_DIRS carrying only east and south is the whole guarantee: for any
    // seam, exactly one of the two tiles has the other in a banding direction.
    try std.testing.expectEqual(@as(usize, 2), BAND_DIRS.len);
    for (BAND_DIRS) |d| {
        // east (1) and south (2) are exactly the two directions that point at
        // the next tile in row-major order
        try std.testing.expect(d == 1 or d == 2);
    }
    // and the opposite of each is absent, so no seam is claimed twice
    for (BAND_DIRS) |d| {
        const opposite: usize = (d + 2) % 4;
        for (BAND_DIRS) |e| try std.testing.expect(e != opposite);
    }

    // A band's ramp must run the right way round too: most of the neighbour at
    // the shared edge, least of it back inside this tile. A reversed ramp
    // reproduces the same visible artifact from the other direction.
    for (0..TILE_COUNT) |b| {
        if (!bandsWith(@intCast(b))) continue;
        for (BAND_DIRS) |d| {
            var at_edge: usize = 0;
            var at_back: usize = 0;
            for (0..T) |yy| {
                for (0..T) |xx| {
                    const along: usize = if (d == 1) T - 1 - xx else T - 1 - yy;
                    if (BANDS[b][dirSlot(d)][0][yy * T + xx] == 0) continue;
                    if (along == 0) at_edge += 1;
                    if (along + 1 == BAND) at_back += 1;
                }
            }
            // the shared edge is where the two tiles meet, so it must be the
            // most-blended line; the far end of the band is back in this tile
            try std.testing.expect(at_edge > at_back);
        }
    }
}

test "the cart has no leftover debug scaffolding" {
    // Temporary screenshot rigs kept leaking into the cart -- a pinned camera
    // silently blocked the arrow keys, a pinned cursor pinned the hover box,
    // and a stray `if (true)` swallowed the HUD gating. All three shipped
    // because nothing failed loudly: the cart still ran, it just stopped
    // responding. These are the shapes that rig took, checked at build time.
    //
    // The camera may only be written by input() (arrows, Z recentre) and by
    // boot(). Anything assigning it in update() pins movement, and a pin placed
    // after input() wins over the keys entirely.
    // Scan only the cart itself, not the checks below -- otherwise every
    // needle here would match its own literal and the test would always fail.
    const all = @embedFile("cart.zig");
    const body = all[0..std.mem.indexOf(u8, all, "// -- checks").?];

    // no unconditional branch, which is how every one of these hid in plain sight
    try std.testing.expect(std.mem.indexOf(u8, body, "if (true)") == null);
    try std.testing.expect(std.mem.indexOf(u8, body, "cam_x = 210") == null);
    try std.testing.expect(std.mem.indexOf(u8, body, "cam_y = 300") == null);
    // a hardcoded mouse read is the same bug in the hover box
    try std.testing.expect(std.mem.indexOf(u8, body, "cam_x + 137") == null);

    // the clamp has to exist, and has to sit after the arrow keys
    const clamp_at = std.mem.indexOf(u8, body, "std.math.clamp(cam_x").?;
    const last_key = std.mem.lastIndexOf(u8, body, "cam_x += speed").?;
    try std.testing.expect(clamp_at > last_key);
}

test "tile art never uses palette 0, which is the band transparency key" {
    // The transition bands blit with key 0, so a terrain pixel painted 0 would
    // be skipped and the tile underneath would show through it -- holes in the
    // map wherever the art happened to touch index 0. JONK 16's index 0 is a
    // dark blue-grey rather than black, so this is not even a colour anyone
    // would reach for deliberately; it is a silent failure.
    for (0..TILE_COUNT) |t| {
        for (0..VARIANTS) |v| for (0..2) |f| for (0..NP) |i| {
            try std.testing.expect(TILES[t].art[v][f][i] != 0);
        };
        // the bands themselves are meant to use it, and only it
        for (BANDS[t][0][0]) |px| {
            try std.testing.expect(px == 0 or (px >= 1 and px <= 15));
        }
    }
}

test "the palette table is the one the art is drawn against" {
    // 16 entries, and the roles must stay inside it
    try std.testing.expectEqual(@as(usize, 16), JONK16.len);
    inline for (@typeInfo(C).@"struct".decls) |d| {
        const v = @field(C, d.name);
        if (@TypeOf(v) != u8) continue;
        try std.testing.expect(v < 16);
    }
}

test "edge scroll is signed and points away from the edge it is against" {
    // Idle away from the edges, so the world does not creep under a still cursor.
    try std.testing.expectEqual(@as(i32, 0), edgeScroll(EDGE, vex.WIDTH));
    try std.testing.expectEqual(@as(i32, 0), edgeScroll(vex.WIDTH - 1 - EDGE, vex.WIDTH));
    try std.testing.expectEqual(@as(i32, 0), edgeScroll(vex.WIDTH / 2, vex.WIDTH));
    try std.testing.expectEqual(@as(i32, 0), edgeScroll(vex.HEIGHT / 2, vex.HEIGHT));

    // Full speed pinned to each edge, and pointing the right way: the cursor on
    // the left of the screen has to scroll the camera left, not right. Getting
    // this sign wrong is a silent half-control -- the camera only travels one
    // way along the axis and nothing looks broken enough to notice.
    try std.testing.expectEqual(-EDGE_SPEED, edgeScroll(0, vex.WIDTH));
    try std.testing.expectEqual(EDGE_SPEED, edgeScroll(vex.WIDTH - 1, vex.WIDTH));
    // y is measured over the full screen, HUD strip included, so the very
    // bottom row of the screen scrolls down rather than the last row of the map
    // doing it instead
    try std.testing.expectEqual(-EDGE_SPEED, edgeScroll(0, vex.HEIGHT));
    try std.testing.expectEqual(EDGE_SPEED, edgeScroll(vex.HEIGHT - 1, vex.HEIGHT));

    // Left ramp, walking from the margin out to the edge: never positive, and
    // the speed grows as the cursor nears the edge.
    var prev = edgeScroll(EDGE, vex.WIDTH);
    try std.testing.expectEqual(@as(i32, 0), prev);
    for (1..EDGE + 1) |d| {
        const s = edgeScroll(@intCast(EDGE - d), vex.WIDTH);
        try std.testing.expect(s <= prev);
        try std.testing.expect(s <= 0);
        try std.testing.expect(s >= -EDGE_SPEED);
        prev = s;
    }
    try std.testing.expectEqual(-EDGE_SPEED, prev); // at m = 0

    // Right ramp, same walk, and never negative.
    var prev_r = edgeScroll(vex.WIDTH - 1 - EDGE, vex.WIDTH);
    try std.testing.expectEqual(@as(i32, 0), prev_r);
    for (1..EDGE + 1) |d| {
        const s = edgeScroll(@intCast(vex.WIDTH - 1 - EDGE + d), vex.WIDTH);
        try std.testing.expect(s >= prev_r);
        try std.testing.expect(s >= 0);
        try std.testing.expect(s <= EDGE_SPEED);
        prev_r = s;
    }
    try std.testing.expectEqual(EDGE_SPEED, prev_r); // at m = WIDTH-1
}

test "edge scroll never reverses anywhere the mouse can actually reach" {
    // The sign is the whole control: negative scrolls toward 0, positive toward
    // the far edge. A cursor position producing the opposite sign would send the
    // camera the wrong way, and since it is a whole number of pixels either side
    // of a boundary, it reads as a dead row rather than as a bug.
    //
    // The mouse ranges over [0, extent-1] and nothing more, so that is exactly
    // what gets swept -- an off-by-one at either end is enough to flip a sign.
    //
    // Zero is allowed throughout the margins: with only EDGE_SPEED steps to
    // spend, the inner few pixels of the easing zone round down to no movement
    // at all, which is the intended ramp, not a fault.
    inline for (.{ vex.WIDTH, vex.HEIGHT }) |extent| {
        var m: i32 = 0;
        while (m < extent) : (m += 1) {
            const s = edgeScroll(m, extent);
            if (m < EDGE) {
                try std.testing.expect(s <= 0);
            } else if (m <= extent - 1 - EDGE) {
                try std.testing.expectEqual(@as(i32, 0), s);
            } else {
                try std.testing.expect(s >= 0);
            }
        }
    }
    // and the dead zone really is dead: the whole middle of both axes
    try std.testing.expectEqual(@as(i32, 0), edgeScroll(EDGE, vex.WIDTH));
    try std.testing.expectEqual(@as(i32, 0), edgeScroll(vex.WIDTH - 1 - EDGE, vex.WIDTH));
    try std.testing.expectEqual(@as(i32, 0), edgeScroll(EDGE, vex.HEIGHT));
    try std.testing.expectEqual(@as(i32, 0), edgeScroll(vex.HEIGHT - 1 - EDGE, vex.HEIGHT));
}

test "clicking the overview picks the tile under the pointer, and only that" {
    // On the map: it is drawn 1:1, so the tile is the offset from the origin.
    // Derived from the map constants rather than hardcoded, so it stays honest
    // if the map is resized -- at 320x160 the map fills the area exactly and
    // there is no longer any screen point that is off the left or top of it.
    const tl = overviewTileAt(MAP_X, MAP_Y).?;
    try std.testing.expectEqual(@as(i32, 0), tl.x);
    try std.testing.expectEqual(@as(i32, 0), tl.y);
    const br = overviewTileAt(MAP_X + @as(i32, @intCast(MAP_W)) - 1, MAP_Y + @as(i32, @intCast(MAP_H)) - 1).?;
    try std.testing.expectEqual(@as(i32, @intCast(MAP_W)) - 1, br.x);
    try std.testing.expectEqual(@as(i32, @intCast(MAP_H)) - 1, br.y);

    // One pixel past any edge is off the map, and must be refused rather than
    // recentring on a tile the player never pointed at.
    try std.testing.expect(overviewTileAt(MAP_X - 1, MAP_Y) == null);
    try std.testing.expect(overviewTileAt(MAP_X, MAP_Y - 1) == null);
    try std.testing.expect(overviewTileAt(MAP_X + @as(i32, @intCast(MAP_W)), MAP_Y) == null);
    try std.testing.expect(overviewTileAt(MAP_X, MAP_Y + @as(i32, @intCast(MAP_H))) == null);
    // the HUD strip sits below the map and is not part of it
    try std.testing.expect(overviewTileAt(0, HUD_Y) == null);
}

test "the map fits the screen, and its cell indices fit the sentinel" {
    // The overview is 1px per tile, so the map is bounded by the drawable area.
    try std.testing.expect(MAP_W <= @as(usize, @intCast(vex.WIDTH)));
    try std.testing.expect(MAP_H <= @as(usize, @intCast(HUD_Y)));
    // Cells are addressed as u16 to keep the arrays small, with NO_CELL as the
    // terminator -- so a map one cell too large would alias the terminator and
    // quietly corrupt the lists rather than fail to compile.
    try std.testing.expect(CELLS < NO_CELL);
}

test "the entropy lists stay consistent with the cells they hold" {
    // The lists are the only thing standing between the solver and a quadratic
    // rescan, and a broken one is silent: the map still solves, it just stops
    // picking the most constrained cell, and contradictions quietly get more
    // common. So check the structure, not just the result.
    var linked: usize = 0;
    for (0..CELLS) |i| {
        const n: u8 = @intCast(@popCount(masks[i]));
        const b = bucket_of[i];
        if (n <= 1) {
            // decided cells must be off the lists, or they get collapsed twice
            try std.testing.expectEqual(@as(u8, 0xFF), b);
            continue;
        }
        try std.testing.expect(b == n); // on the list for its own options
        try std.testing.expect(b >= 2 and b <= MAX_ENTROPY);
        // links point to cells that are actually in that list
        if (bucket_next[i] != NO_CELL) {
            try std.testing.expectEqual(b, bucket_of[bucket_next[i]]);
        }
        if (bucket_prev[i] != NO_CELL) {
            try std.testing.expectEqual(@as(u16, @intCast(i)), bucket_next[bucket_prev[i]]);
        } else {
            try std.testing.expectEqual(@as(u16, @intCast(i)), bucket_head[b]);
        }
        linked += 1;
    }
    // every undecided cell is reachable, i.e. some list is non-empty
    const reached: usize = linked;
    var b: usize = 2;
    while (b <= MAX_ENTROPY) : (b += 1) {
        var walk: u16 = bucket_head[b];
        var guard: usize = 0;
        while (walk != NO_CELL) : (walk = bucket_next[walk]) {
            try std.testing.expect(guard < CELLS); // no cycles
            try std.testing.expectEqual(b, bucket_of[walk]);
            guard += 1;
        }
    }
    try std.testing.expect(reached == linked);
    // and pickCell agrees with the structure: it returns a minimum, and null
    // only when nothing is left to decide
    if (pickCell()) |c| {
        try std.testing.expect(@popCount(masks[c]) > 1);
        var best: u8 = MAX_ENTROPY + 1;
        for (0..CELLS) |i| {
            const n: u8 = @intCast(@popCount(masks[i]));
            if (n > 1) best = @min(best, n);
        }
        try std.testing.expectEqual(best, @as(u8, @intCast(@popCount(masks[c]))));
    } else {
        for (0..CELLS) |i| try std.testing.expect(@popCount(masks[i]) == 1);
    }
}

test "the mouse only moves the camera while the button is held" {
    // The bug this guards: a pointer resting near a screen edge used to be
    // enough. The cart boots with the pointer wherever the console last left
    // it, so an unfocused window reporting (0, 0) walked the camera to the top
    // left of the map and kept going -- no input, no visible cause.
    //
    // Held is checked before anything else that could permit a scroll, so the
    // truth table below is the whole rule: any `held` of false means no
    // movement, whatever the other two are.
    try std.testing.expect(!edgeScrollAllowed(false, false, false));
    try std.testing.expect(!edgeScrollAllowed(false, false, true));
    try std.testing.expect(!edgeScrollAllowed(true, false, false));
    try std.testing.expect(!edgeScrollAllowed(true, false, true));
    // And the ways it *is* allowed, so the check cannot pass by always
    // returning false.
    try std.testing.expect(edgeScrollAllowed(false, true, true));
    try std.testing.expect(!edgeScrollAllowed(true, true, true)); // nothing to scroll to
    try std.testing.expect(!edgeScrollAllowed(false, true, false)); // off-screen pointer
}

test "a held mouse button reads as one press, not one per frame" {
    // There is no mbtnp(): mbtn() is held only. Anything bound to it has to
    // find the rising edge itself, or a toggle flips every frame the button is
    // down and lands on whichever side an odd number of frames left it.
    //
    // The whole truth table, because the failure is in the two cases that
    // look harmless: staying down must not re-fire, and releasing must not
    // fire either.
    try std.testing.expect(justPressed(true, false)); // down this frame: the press
    try std.testing.expect(!justPressed(true, true)); // still down: no
    try std.testing.expect(!justPressed(false, true)); // released: no
    try std.testing.expect(!justPressed(false, false)); // untouched: no

    // A press-and-hold is exactly one press, whatever the frame rate.
    var was_down = false;
    var presses: usize = 0;
    for (0..60) |_| {
        if (justPressed(true, was_down)) presses += 1;
        was_down = true;
    }
    try std.testing.expectEqual(@as(usize, 1), presses);
}

test "every HUD line fits the screen in the 8x8 font" {
    // A hint line that overruns is not visibly broken. text() clips at the
    // screen edge, so the line just stops -- "ARROWS SCROLL   HOLD LMB AT EDGE
    //   X OR RMB MAP   Z NEW" was 55 glyphs against 39 that fit, and the last
    // sixteen characters were silently dropped, taking the new-world binding
    // with them. Nothing fails, nothing looks wrong at a glance.
    //
    // So the fit is checked, not eyeballed. The seed line is included at its
    // widest: 8 hex digits, the far-corner coordinate, and the longest tile
    // name, which is what actually decides whether that line overflows.
    const cap = (vex.WIDTH - 2 * HUD_MARGIN) / CHAR_W;
    const seed_line = "SEED FFFFFFFF  319,159  SNOWCAP";
    inline for (.{ seed_line, HINT_SCROLL, HINT_MAP }) |line| {
        try std.testing.expect(@as(i32, @intCast(line.len)) <= cap);
    }
    // And the font assumption itself, so a console font change fails here rather
    // than as a silently clipped line much later.
    try std.testing.expectEqual(@as(i32, 39), cap);
}

test "every elevation tier gets a visible share of the land" {
    // The tiers were all reachable and the palette ramp was correct, and the
    // highlands still read as one flat colour -- because the band edges gave
    // rock five times the area of peaks, so rock filled the frame and the rest
    // were thin edges. Reachability is not the same as visibility.
    //
    // Measured over six seeds, as a share of the map:
    //     6.15  rock      3.12  scree    1.11  peaks    0.19  snow
    // which is a geometric shrink, and a map is mostly a gradient of its
    // largest term. The edges are now fitted to the height distribution's
    // quantiles instead, which is what the numbers below assert.
    const seeds = [_]u32{ 0x51ED, 0x7A3F, 0x2C91, 0xFEED, 0x1234, 0xABCD };
    var counts: [TILE_COUNT]u32 = @splat(0);
    var total: u32 = 0;
    for (seeds) |s| {
        _ = reset(s);
        var guard: usize = 0;
        while (!solved and guard < 100) : (guard += 1) _ = solve(CELLS);
        for (0..CELLS) |i| {
            counts[world[i]] += 1;
            total += 1;
        }
    }
    const n: f32 = @floatFromInt(total);
    const land = [_]u8{ GRASS, FOREST, FOREST_DEEP, ROCK, ROCK_HIGH, PEAK, SNOW };

    // Water is not part of the gradient, so it is excluded from the floor: a
    // world can be nearly all ocean and still be fine.
    for (land) |t| {
        try std.testing.expect(100.0 * @as(f32, @floatFromInt(counts[t])) / n > 0.8);
    }
    // And the ramp must not collapse back to one dominant term. The largest
    // land tier may not swamp the smallest by more than 12:1. It is currently
    // 8:1 (forest 11.97% against snow 1.49%) and was 32:1, which is what made
    // the highlands read as one colour: rock at 6.15% beside peaks at 1.11% and
    // snow at 0.19%, so the frame was almost entirely rock.
    var lo: f32 = 1e9;
    var hi: f32 = 0;
    for (land) |t| {
        const s2: f32 = 100.0 * @as(f32, @floatFromInt(counts[t])) / n;
        lo = @min(lo, s2);
        hi = @max(hi, s2);
    }
    try std.testing.expect(hi / lo < 12.0);
}
