//! vex-world -- a procedural overworld assembled by wave function collapse.
//!
//! A 48x32 tile map is generated by starting every cell as "any tile" and
//! repeatedly collapsing the cell with the fewest options left, propagating the
//! constraint to its neighbours. Tiles are opaque 16x16 palette bitmaps blitted
//! straight into the framebuffer, so a finished world is 1536 blits a frame.
const std = @import("std");
const vex = @import("vex");

// -- palette ----------------------------------------------------------------
// JONK 16, applied over the console's default SWEETIE-16 in boot().
//
// The art names colours by role rather than by index, so trying another palette
// means editing this block and the table in boot(), and nothing else. That is
// not tidiness: the roles encode relationships, not preferences. Deep water has
// to be exactly one step darker than shallows, forest darker than grass, and a
// crest on one terrain has to be the body tone of the next. Written as raw
// indices the art hides all of that, and swapping palettes then silently turns
// grass into steel blue and snow into dark brown -- which is exactly what
// happened to the first version of this file.
const JONK16 = [16]u32{
    0x242e36, 0x455951, 0x798766, 0xb7bca2,
    0xd6d6d6, 0xf4f0ea, 0x6988a1, 0xa1b0be,
    0x595b7c, 0x95819d, 0xc9a5a9, 0xf4dec2,
    0x704f4f, 0xb7635b, 0xe39669, 0xebc790,
};

/// Index 0 is reserved and never appears in tile art: it is the blit
/// transparency key for the transition bands, so a terrain pixel painted 0
/// would punch a hole in the map.
const C = struct {
    // water, deepest first. A crest tone is the next depth's body tone, so a
    // shoreline ramps continuously instead of stepping.
    const water_deep: u8 = 8; // #595b7c muted indigo
    const water: u8 = 6; // #6988a1 steel blue
    const water_crest: u8 = 7; // #a1b0be pale blue
    const water_channel: u8 = 9; // #95819d, a lighter deep
    const water_deepest: u8 = 1; // #455951 dark slate
    const shoal: u8 = 15; // #ebc790, sand showing through

    const grass: u8 = 2; // #798766 olive
    const grass_light: u8 = 3; // #b7bca2 pale sage
    const flower: u8 = 11; // #f4dec2 cream
    const forest: u8 = 1; // #455951 dark slate green
    const forest_light: u8 = 2; // #798766 olive, same family as the grass

    const sand: u8 = 15; // #ebc790
    const sand_dark: u8 = 14; // #e39669

    const rock: u8 = 9; // #95819d dusty purple
    const rock_light: u8 = 4; // #d6d6d6
    const rock_dark: u8 = 12; // #704f4f

    const snow: u8 = 5; // #f4f0ea
    const snow_shade: u8 = 4; // #d6d6d6
    const snow_tint: u8 = 7; // #a1b0be

    const roof: u8 = 13; // #b7635b terracotta
    const wall: u8 = 4; // #d6d6d6
    const timber: u8 = 12; // #704f4f

    const ui_bg: u8 = 0; // #242e36
    const ui_dim: u8 = 1; // #455951
    const ui_text: u8 = 4; // #d6d6d6
    const ui_bright: u8 = 5; // #f4f0ea
    const ui_fill: u8 = 2; // #798766
};

// -- world geometry ---------------------------------------------------------

const T: usize = 16; // tile edge, px
const MAP_W: usize = 128;
const MAP_H: usize = 96;
const CELLS: usize = MAP_W * MAP_H;

const VIEW_W: i32 = vex.WIDTH / @as(i32, @intCast(T)); // 20
const VIEW_H: i32 = (vex.HEIGHT - 20) / @as(i32, @intCast(T)); // 10
const HUD_Y: i32 = vex.HEIGHT - 20;
const MAX_CAM_X: i32 = @as(i32, @intCast(MAP_W * T)) - vex.WIDTH;
const MAX_CAM_Y: i32 = @as(i32, @intCast(MAP_H * T)) - VIEW_H * @as(i32, @intCast(T));

const GENERATE_PER_FRAME: usize = 96; // keeps a full solve at ~0.3 s

// -- tiles ------------------------------------------------------------------

const Kind = enum(u8) { deep, shallow, sand, grass, forest, rock, snow, ruins };

const DEEP: u8 = 0;
const SHALLOW: u8 = 1;
const SAND: u8 = 2;
const GRASS: u8 = 3;
const FOREST: u8 = 4;
const ROCK: u8 = 5;
const SNOW: u8 = 6;
const RUINS: u8 = 7;
const TILE_COUNT: usize = 8;
const ALL_TILES: u16 = (@as(u16, 1) << TILE_COUNT) - 1;

/// How many looks each tile kind gets, chosen per map position at draw time so
/// a kind is never the same texture twice in a row. The visible repeat period
/// goes as T * sqrt(VARIANTS), so 4 repeats about every 32px and 8 about every
/// 45px -- enough that grass and sand stop reading as wallpaper.
///
/// Costs 2 KB per variant across art and bands, so this is the knob to turn
/// back down if the wasm gets too big. It only helps the *noise* tiles: ruins
/// needed a different fix entirely, see tileArt.
const VARIANTS: usize = 8;

/// `only` is a hand-written neighbour whitelist: a tile with one may only
/// touch the tiles in it. Everything else falls back to the class rule, so
/// plain terrain blends by elevation while ruins stay put.
const Tile = struct {
    kind: Kind,
    cls: u8, // elevation band: neighbouring classes must be within 1
    weight: u16, // relative pick weight once a cell collapses
    only: u16, // 0 = use the class rule
    name: [:0]const u8,
    /// Representative colour for the one-pixel-per-tile overview. The art's
    /// body tone rather than a corner pixel, which could be a wave crest or a
    /// speckle and would make the map flicker between shades of the same sea.
    map: u8,
    /// [variant][frame]. The frame index is the animation phase and only the
    /// water tiles use it; the variant is picked per map position at draw time
    /// so the same tile kind does not stamp one identical texture everywhere.
    art: [VARIANTS][2][T * T]u8 = @splat(@splat(@splat(0))),
};

const TILES: [TILE_COUNT]Tile = blk: {
    var list: [TILE_COUNT]Tile = .{
        .{ .kind = .deep, .cls = 0, .weight = 6, .only = 0, .name = "DEEP SEA", .map = C.water_deep },
        .{ .kind = .shallow, .cls = 1, .weight = 6, .only = 0, .name = "SHALLOWS", .map = C.water },
        .{ .kind = .sand, .cls = 2, .weight = 5, .only = 0, .name = "BEACH", .map = C.sand },
        .{ .kind = .grass, .cls = 3, .weight = 100, .only = 0, .name = "PLAINS", .map = C.grass },
        .{ .kind = .forest, .cls = 4, .weight = 8, .only = 0, .name = "FOREST", .map = C.forest },
        .{ .kind = .rock, .cls = 5, .weight = 3, .only = 0, .name = "HIGHLANDS", .map = C.rock },
        .{ .kind = .snow, .cls = 6, .weight = 2, .only = 0, .name = "SNOWCAP", .map = C.snow },
        // a landmark: same elevation band as the plains, so it clusters there
        // instead of speckling the whole map. Weight 1 against plains' 100 is
        // roughly one ruin per hundred cells, and ruins may touch ruins, so
        // they settle into little villages rather than singletons.
        .{ .kind = .ruins, .cls = 3, .weight = 1, .only = bit(SAND) | bit(GRASS) | bit(FOREST) | bit(RUINS), .name = "RUINS", .map = C.roof },
    };
    for (&list) |*t| for (0..2) |f| for (0..VARIANTS) |v| {
        t.art[v][f] = tileArt(t.kind, f, v);
    };
    break :blk list;
};

fn bit(t: u8) u16 {
    return @as(u16, 1) << @intCast(t);
}

/// May `a` sit next to `b`? Whitelists win over the elevation rule, and are
/// checked on both sides so the relation stays symmetric.
fn adjacent(a: u8, b: u8) bool {
    if (TILES[a].only != 0) return TILES[a].only & bit(b) != 0;
    if (TILES[b].only != 0) return TILES[b].only & bit(a) != 0;
    return @abs(@as(i32, TILES[a].cls) - @as(i32, TILES[b].cls)) <= 1;
}

const DX = [4]i32{ 0, 1, 0, -1 };
const DY = [4]i32{ -1, 0, 1, 0 };
const OPP = [4]usize{ 2, 3, 0, 1 };

/// `ALLOWED[dir][tile]` = every tile that may touch it on that side.
const ALLOWED: [4][TILE_COUNT]u16 = blk: {
    var out: [4][TILE_COUNT]u16 = @splat(@splat(0));
    for (0..4) |d| for (0..TILE_COUNT) |a| for (0..TILE_COUNT) |b| {
        if (adjacent(@intCast(a), @intCast(b))) out[d][a] |= @as(u16, 1) << @intCast(b);
    };
    break :blk out;
};

// -- tile art ---------------------------------------------------------------
// Every tile is generated at comptime from a small hand-written pattern, so
// the set costs no source bytes beyond the rules above.

const NP: usize = T * T;

fn hash(x: u32, y: u32, s: u32) u32 {
    var v = x *% 0x9E3779B1 +% y *% 0x85EBCA77 +% s *% 0xC2B2AE3D;
    v ^= v >> 15;
    v *%= 0x2545F491;
    v ^= v >> 13;
    return v;
}

/// Spacing of the wave crests, in the `x + y` sum. It must divide T: draw()
/// animates the sea by folding the tile's map position into `phase`, so the
/// tile term only cancels when the period is a factor of the tile size. With a
/// period that does not divide T every tile's wave is shifted by a different
/// amount and the water breaks up along the grid instead of rolling as one body.
const CREST_PERIOD: usize = 16;

/// One period of a sine, sampled by position to bend the crests.
///
/// A straight, evenly spaced 45-degree line reads as hatching, not water: the
/// regularity is the problem, not the colour. Warping the crest coordinate
/// turns it into a curve and, because the warp is steeper in some places than
/// others, the crests also bunch and spread instead of marching in lockstep.
///
/// The warp has to be periodic with the tile. Sampling this table by local
/// position makes it exactly so, which is what keeps the curves continuous
/// across tile edges -- a warp that is not periodic tears the sea along the
/// grid, the same failure the crest period has to avoid.
const SINE = [16]i32{ 0, 2, 4, 5, 6, 5, 4, 2, 0, -2, -4, -5, -6, -5, -4, -2 };

/// How far to push the crest at this pixel, in px. Summed over both axes so
/// the crest bends along its length instead of merely shifting sideways.
///
/// The 1/3 divisor sets the bend. Straight ahead of this, 1/2 bends harder but
/// the crests curl apart into scattered hooks and stop reading as a swell; 1/3
/// keeps them as continuous lines that roll.
fn waveWarp(x: usize, y: usize) i32 {
    return @divTrunc(SINE[x % SINE.len] + SINE[y % SINE.len], 3);
}

fn crest(x: usize, y: usize, phase: usize) bool {
    const u: i32 = @as(i32, @intCast(x + y)) + waveWarp(x, y) + @as(i32, @intCast(phase));
    return @mod(u, @as(i32, @intCast(CREST_PERIOD))) == 0;
}

/// Water tones, deepest first. Deliberately a contiguous ramp: DEEP_CREST is
/// exactly SHALLOW's body, so the two tiles differ by one step and a shoreline
/// reads as shoaling water rather than as two unrelated colours meeting.
const DEEP_BODY: u8 = C.water_deep;
const DEEP_CREST: u8 = C.water;
const SHALLOW_BODY: u8 = C.water;
const SHALLOW_CREST: u8 = C.water_crest;

// -- transition bands --------------------------------------------------------
// Where two kinds meet, the tile boundary is a hard 16px seam. A band dithers
// the two terrains into each other across that edge.
//
// The band has to carry *both* sides. Carrying only the neighbour's texture --
// the obvious cheap version -- stamps one terrain's grain over the other and
// reads as a line laid on top of the map rather than a transition. A full
// per-pair tileset would be the other extreme, and still could not cover a tile
// with three different neighbours, so the blend stays an overlay.

/// How far the blend reaches in from the edge, in px.
const BAND: usize = 8;

/// 4x4 ordered dither, the classic pixel-art crosshatch. Deliberately a fixed
/// matrix and not noise: the regular weave is what makes the fade look
/// deliberate rather than dirty.
const BAYER4 = [16]u8{ 0, 8, 2, 10, 12, 4, 14, 6, 3, 11, 1, 9, 15, 7, 13, 5 };

/// `other` dithered in over the half of the tile facing side `dir`, where
/// `other` is the neighbour that way, drawn as `variant`. 0 means "let this
/// tile show through"; no art uses palette 0, so 0 is also the blit key.
///
/// The blend only covers the half of the tile nearest the neighbour, and only
/// this tile draws. Blending the whole tile, or blending on both sides of a
/// seam, makes the two bands overlap across the whole boundary: the transition
/// comes out 16px wide with each terrain visible on the far side of the other.
///
/// `variant` is the *neighbour's* variant and is not optional. Bands keyed on
/// kind alone made the squares show: the blend carried variant 0's texture
/// while the neighbouring tile drew a random variant, so every seam mismatched,
/// and one wobble pattern repeated with period 16 across the world. Anywhere
/// three terrains interleave -- beach, shallows, deep sea -- the seams are
/// frequent enough that the shared wobble read as a 16px grid.
fn bandArt(other: u8, dir: usize, variant: usize) [NP]u8 {
    @setEvalBranchQuota(200_000);
    const salt: u32 = 0xB0 +% @as(u32, other) * 31 +% @as(u32, @intCast(variant)) * 7;
    var px: [NP]u8 = @splat(0);
    for (0..T) |yy| for (0..T) |xx| {
        // how far in from the facing edge this pixel is
        const along: usize = switch (dir) {
            0 => yy, // north
            1 => T - 1 - xx, // east
            2 => T - 1 - yy, // south
            else => xx, // west
        };
        if (along >= BAND) continue;
        const wob: i32 = @as(i32, @intCast(hash(xx / 2, yy / 2, salt) % 5)) - 2;
        // Clamp at 0, do not skip. `along` is 0 on the shared edge with the
        // neighbour, and a negative wobble there skipped the pixel entirely,
        // letting the base tile show through -- a bare seam line across the one
        // place the two terrains are supposed to actually meet. The wobble may
        // only eat into the band from the inside.
        const t: i32 = @max(0, @as(i32, @intCast(along)) + wob);
        if (t >= BAND) continue; // wobble pushed it out of the band
        // 0 = all neighbour (on the edge), BAND = all this tile (back inside)
        if (BAYER4[(yy % 4) * 4 + (xx % 4)] * BAND >= t * 16) {
            px[yy * T + xx] = TILES[other].art[variant][0][yy * T + xx];
        }
    };
    return px;
}

/// Which sides draw a band: east and south only.
///
/// A seam must be blended exactly once. With all four sides enabled, the sand
/// tile west of a grass tile fades grass in across its east half *and* the
/// grass tile fades sand in across its west half, so the two overlap across
/// the whole boundary: green spikes up to full at the beach, collapses back to
/// bare sand inside the plains, then recovers. That reads as green being
/// denser on the beach side than the plains side, which is exactly backwards.
///
/// Restricting to east and south makes the tile earlier in row-major order the
/// sole owner of each seam, so the blend is a single ramp with no second
/// counter-ramp fighting it.
const BAND_DIRS = [2]usize{ 1, 2 }; // east, south

/// Ruins are excluded because they are a building standing *on* the plains, not
/// a terrain of their own: blending them would dither grass through the walls
/// and scatter roof onto the grass next door.
fn bandsWith(t: u8) bool {
    return t != RUINS;
}

fn dirSlot(d: usize) usize {
    const i: usize = if (d == BAND_DIRS[0]) 0 else 1;
    return i;
}

const BANDS: [TILE_COUNT][BAND_DIRS.len][VARIANTS][NP]u8 = blk: {
    var out: [TILE_COUNT][BAND_DIRS.len][VARIANTS][NP]u8 = undefined;
    for (0..TILE_COUNT) |b| for (BAND_DIRS, 0..) |d, di| for (0..VARIANTS) |v| {
        out[b][di][v] = bandArt(@intCast(b), d, v);
    };
    break :blk out;
};

fn tileArt(comptime kind: Kind, comptime phase: usize, comptime variant: usize) [NP]u8 {
    @setEvalBranchQuota(4_000_000);
    var px: [NP]u8 = @splat(0);
    for (0..T) |yy| for (0..T) |xx| {
        const n = hash(@intCast(xx), @intCast(yy), @as(u32, @intFromEnum(kind)) * 977 +%
            @as(u32, @intCast(variant)) * 331 +% phase * 7 +% 1);
        // Noise for the wave itself, deliberately *not* seeded by `kind` or
        // `variant`: both water tiles have to break their crest along the same
        // lines, or the ripple runs on across a DEEP/SHALLOWS join but its gaps
        // do not, and any two water tiles can meet at any variant pair.
        const w = hash(@intCast(xx), @intCast(yy), phase * 7 +% 1);
        // Body noise for the water tiles. Per-pixel, and deliberately *not*
        // seeded by `phase`: a coarse grain at this contrast reads as a grid of
        // blocks (4x4 blotches of 8 against 9 were plainly a checkerboard), and
        // a phase-seeded one would make the texture shimmer with the wave. Fine
        // grain only works at low contrast -- which is why the forest's
        // three-tone dither passes and this did not.
        const d = hash(xx, yy, 0xDEE9 +% @as(u32, @intFromEnum(kind)) * 13 +%
            @as(u32, @intCast(variant)) * 5);
        var c: u8 = 8;
        switch (kind) {
            // Water is a depth ramp: DEEP sits on 9 and SHALLOWS on 10, one
            // step apart, so a shoreline reads as shoaling rather than as dark
            // paint meeting light paint. An earlier DEEP was flat 8, several
            // steps from SHALLOWS 9, and read as a void with lines drawn on it.
            // The mottle is what stops either of them looking like a solid fill.
            .deep => c = if (d % 11 == 0) C.water_channel else if (d % 37 == 0) C.water_deepest else DEEP_BODY,
            .shallow => c = if (d % 11 == 0) DEEP_BODY else if (d % 29 == 0) C.shoal else SHALLOW_BODY,
            .sand => c = if (n % 17 == 0) C.sand_dark else if (n % 11 == 0) C.flower else C.sand,
            .grass => c = if (n % 53 == 0) C.flower else if (n % 19 == 0) C.grass_light else C.grass,
            // Forest is dither, not drawn crowns. An earlier version painted
            // round canopies, but any shape big enough to read as a tree is
            // also big enough that a per-tile variant tears it at the tile
            // border -- and a few round blobs sitting on light green read as
            // bushes, not forest.
            //
            // Two layers, because each alone was wrong. Pure 2x2 blocks at this
            // contrast were a visible lattice, and that lattice sits inside
            // *every* variant, so adding variants only reproduced it. Pure
            // per-pixel dither went the other way and the tile just read as
            // darker grass, with no canopy to it. So: a 2x2 block picks how much
            // dark canopy a patch holds, and a per-pixel dither lays the pixels
            // down inside it. The dither breaks the block edges, the blocks give
            // the dither shade to vary across, and neither is visible alone.
            .forest => {
                const b = hash(xx / 2, yy / 2, 0x5EED +% @as(u32, @intCast(variant)));
                // how much of the patch is dark canopy: 7 is the shaded tone
                const dark: u32 = switch (b % 3) {
                    0 => 8, // deep shade
                    1 => 5, // even
                    else => 2, // sunlit, mostly showing the grass beneath
                };
                c = if (n % 10 < dark) C.forest else C.forest_light;
            },
            .rock => c = if (n % 13 == 0) C.rock_light else if (n % 19 == 0) C.rock_dark else C.rock,
            .snow => c = if (n % 9 == 0) C.snow_shade else if (n % 23 == 0) C.snow_tint else C.snow,
            // Ruins are the one tile in the set that is not noise, which made
            // them the one tile variants did nothing for: every ruin drew the
            // same house in the same place, so a village came out as a row of
            // photocopies. Buildings may vary freely, unlike the water's wave --
            // nothing has to line up with a neighbour across the tile edge, so
            // each gets its own plan. A building does get cut off at the edge
            // if it lands there, which is fine; it is a structure on a 16px plot.
            .ruins => {
                c = if (n % 19 == 0) C.grass_light else C.grass;
                switch (variant % 4) {
                    0 => { // cottage, gabled roof and a door
                        if (xx >= 3 and xx <= 12 and yy >= 5 and yy <= 11) {
                            c = if (yy <= 7) C.roof else if (yy == 11 or xx == 3 or xx == 12) C.timber else C.wall;
                            if (yy == 9 and xx == 7) c = C.timber;
                        }
                    },
                    1 => { // squat tower, crenellated
                        if (xx >= 5 and xx <= 10 and yy >= 4 and yy <= 12) {
                            c = if (yy == 4 or (yy == 5 and (xx == 5 or xx == 10))) C.timber else C.wall;
                            if (yy >= 7 and yy <= 9 and (xx == 7 or xx == 8)) c = C.timber;
                        }
                    },
                    2 => { // a collapsed wall, roof long gone
                        if (xx >= 2 and xx <= 13 and yy >= 7 and yy <= 10) {
                            if ((xx * 3 + yy * 5) % 7 != 0) c = if (yy == 7) C.roof else C.wall;
                            if (yy == 10) c = C.timber;
                        }
                    },
                    else => { // two low sheds
                        if ((xx >= 2 and xx <= 6 and yy >= 8 and yy <= 11) or
                            (xx >= 9 and xx <= 13 and yy >= 5 and yy <= 8))
                        {
                            c = if (yy == 8 or yy == 5) C.roof else C.wall;
                        }
                    },
                }
            },
        }
        // The crest goes on top of the mottled body, for both water tiles, and
        // always along the same `crest` lines -- that shared wave is what makes
        // a DEEP/SHALLOWS seam read as one body of water. DEEP_CREST is exactly
        // SHALLOW's body tone, so the ramp is continuous across the join: 9
        // deep body, 10 deep crest / shallow body, 11 shallow crest.
        if (kind == .deep or kind == .shallow) {
            if (crest(xx, yy, phase) and w % 2 == 0) {
                c = if (kind == .deep) DEEP_CREST else SHALLOW_CREST;
            }
        }
        px[yy * T + xx] = c;
    };
    return px;
}

// -- target field -----------------------------------------------------------
// The adjacency rules alone give a world of static: every cell is as likely to
// be sea as mountains, and the rules only forbid the jumps in between. So the
// collapse is *aimed* -- a smooth noise field decides the elevation each cell
// would like, and a cell takes the allowed tile closest to it. The rules still
// have the final word, which is what keeps the result consistent.

/// Sea level for the world being generated, jittered per seed so no two worlds
/// have the same amount of ocean.
var sea: f32 = 0.40;

fn lerp(a: f32, b: f32, t: f32) f32 {
    return a + (b - a) * t;
}

/// How high cell `i` wants to be, 0..1. Two octaves of value noise: the coarse
/// one decides where the continents are, the fine one breaks up the coastline.
var height: [CELLS]f32 = @splat(0);
var height_salt: u32 = 0;

fn buildHeight(salt: u32) void {
    // 6x4 and 13x8 lattices: continents and shoreline detail
    var lat: [24 + 13 * 8]f32 = undefined;
    for (0..6 * 4) |i| lat[i] = noiseVal(@intCast(i % 6), @intCast(i / 6), salt +% 11);
    for (0..13 * 8) |i| lat[i + 24] = noiseVal(@intCast(i % 13), @intCast(i / 13), salt +% 907);
    var peak: f32 = 0;
    for (0..MAP_H) |y| for (0..MAP_W) |x| {
        const h = 0.72 * sample(lat[0..24], 6, 4, x, y) + 0.28 * sample(lat[24..], 13, 8, x, y);
        height[y * MAP_W + x] = h;
        peak = @max(peak, h);
    };
    // Scale against this world's own tallest peak. The raw field tops out
    // wherever the lattice rolled, so fixed thresholds would leave snow and
    // rock unreachable on a flat roll and swallow the map on a spiky one.
    if (peak > 0) {
        for (&height) |*h| h.* /= peak;
    }
}

fn noiseVal(x: u32, y: u32, s: u32) f32 {
    return @as(f32, @floatFromInt(hash(x, y, s ^ height_salt) & 0xFFFF)) / 65535.0;
}

/// Bilinear value noise with a smoothstep fade, so the field has no lattice
/// creases -- a straight lerp would band along every lattice line.
fn sample(lat: []const f32, w: usize, h: usize, x: usize, y: usize) f32 {
    const fx = @as(f32, @floatFromInt(x)) * @as(f32, @floatFromInt(w - 1)) / @as(f32, @floatFromInt(MAP_W - 1));
    const fy = @as(f32, @floatFromInt(y)) * @as(f32, @floatFromInt(h - 1)) / @as(f32, @floatFromInt(MAP_H - 1));
    const x0: usize = @intFromFloat(@min(@floor(fx), @as(f32, @floatFromInt(w - 1))));
    const y0: usize = @intFromFloat(@min(@floor(fy), @as(f32, @floatFromInt(h - 1))));
    const tx = fx - @floor(fx);
    const ty = fy - @floor(fy);
    const sx = tx * tx * (3 - 2 * tx);
    const sy = ty * ty * (3 - 2 * ty);
    return lerp(
        lerp(lat[y0 * w + x0], lat[y0 * w + @min(x0 + 1, w - 1)], sx),
        lerp(lat[@min(y0 + 1, h - 1) * w + x0], lat[@min(y0 + 1, h - 1) * w + @min(x0 + 1, w - 1)], sx),
        sy,
    );
}

/// The class a cell would ideally be, from its height. These band edges are
/// the real knobs of the world: they set how much of the map is ocean, how
/// wide the beaches are, and how much of the highlands is snow.
fn wantClass(h: f32) u8 {
    if (h < sea) return DEEP;
    if (h < sea + 0.015) return SHALLOW;
    if (h < sea + 0.035) return SAND;
    if (h < sea + 0.22) return GRASS;
    if (h < sea + 0.45) return FOREST;
    if (h < sea + 0.70) return ROCK;
    return SNOW;
}

var masks: [CELLS]u16 = @splat(ALL_TILES); // tiles still allowed per cell
var world: [CELLS]u8 = @splat(DEEP); // the chosen tile, valid once solved
var queued: [CELLS]bool = @splat(false);
var stack: [CELLS]usize = undefined;
var solved: bool = false;
var seed: u32 = 0xC0FFEE;
var rng: u32 = 0xC0FFEE;
var retries: u32 = 0;
var frame: i32 = 0;
var cam_x: i32 = 0;
var cam_y: i32 = 0;
/// X swaps the scrolling view for the whole world at one pixel per tile.
var zoomed_out: bool = false;

/// Top-left of the 1:1 overview, centred in the area above the HUD.
const MAP_X: i32 = (vex.WIDTH - @as(i32, @intCast(MAP_W))) / 2;
const MAP_Y: i32 = (HUD_Y - @as(i32, @intCast(MAP_H))) / 2;

/// The whole map at one pixel per tile, with the scrolling viewport outlined so
/// you can see where you are and pick a spot to go back to.
fn drawOverview() void {
    vex.cls(C.ui_bg);
    for (0..MAP_H) |y| {
        for (0..MAP_W) |x| {
            vex.pset(MAP_X + @as(i32, @intCast(x)), MAP_Y + @as(i32, @intCast(y)), TILES[world[y * MAP_W + x]].map);
        }
    }
    // the viewport, clamped to the map: the camera can sit low enough that the
    // 11-row window overhangs the last row, and an outline drawn off the edge
    // would just be cut off mid-line
    const vx = @divTrunc(cam_x, @as(i32, @intCast(T)));
    const vy = @divTrunc(cam_y, @as(i32, @intCast(T)));
    const vw = @min(VIEW_W, @as(i32, @intCast(MAP_W)) - vx);
    const vh = @min(VIEW_H, @as(i32, @intCast(MAP_H)) - vy);
    vex.rectb(MAP_X + vx, MAP_Y + vy, vw, vh, C.ui_bright);

    // frame the map so it reads as a map rather than as a small stray image
    vex.rectb(MAP_X - 1, MAP_Y - 1, @as(i32, @intCast(MAP_W)) + 2, @as(i32, @intCast(MAP_H)) + 2, C.ui_dim);

    vex.rect(0, HUD_Y, vex.WIDTH, vex.HEIGHT - HUD_Y, C.ui_bg);
    vex.text(say("SEED {X}  MAP {d}x{d}", .{ seed, MAP_W, MAP_H }), 4, HUD_Y + 2, C.ui_text);
    vex.text("ARROWS MOVE BOX   X BACK TO WORLD", 4, HUD_Y + 11, C.ui_dim);
}

fn rnd() u32 {
    rng ^= rng << 13;
    rng ^= rng >> 17;
    rng ^= rng << 5;
    if (rng == 0) rng = 0xDEADBEEF;
    return rng;
}

/// Push the consequences of `start`'s options out to its neighbours.
/// Returns false on a contradiction, which means this seed is a dead end.
fn propagate(start: usize) bool {
    var sp: usize = 0;
    stack[sp] = start;
    queued[start] = true;
    sp += 1;
    while (sp > 0) {
        sp -= 1;
        const c = stack[sp];
        queued[c] = false;
        const cx = c % MAP_W;
        const cy = c / MAP_W;
        for (0..4) |d| {
            const nx = @as(i32, @intCast(cx)) + DX[d];
            const ny = @as(i32, @intCast(cy)) + DY[d];
            if (nx < 0 or ny < 0 or nx >= MAP_W or ny >= MAP_H) continue;
            const n: usize = @as(usize, @intCast(ny)) * MAP_W + @as(usize, @intCast(nx));

            var allow: u16 = 0;
            var m = masks[c];
            while (m != 0) {
                const t: usize = @ctz(m);
                m &= m - 1;
                allow |= ALLOWED[OPP[d]][t];
            }
            const next = masks[n] & allow;
            if (next == 0) return false;
            if (next != masks[n]) {
                masks[n] = next;
                if (!queued[n]) {
                    queued[n] = true;
                    stack[sp] = n;
                    sp += 1;
                }
            }
        }
    }
    return true;
}

/// The cell with the fewest options left, ties broken by reservoir sampling so
/// every candidate is equally likely. Null once the whole map is decided.
fn pickCell() ?usize {
    var best: usize = 0;
    var best_n: u8 = TILE_COUNT + 1; // one past the widest possible mask
    var seen: u32 = 0; // candidates with the current best_n
    for (0..CELLS) |i| {
        const n: u8 = @intCast(@popCount(masks[i]));
        if (n <= 1) continue;
        if (n < best_n) {
            best_n = n;
            best = i;
            seen = 1;
        } else if (n == best_n) {
            seen += 1;
            if (rnd() % seen == 0) best = i;
        }
    }
    return if (best_n > TILE_COUNT) null else best;
}

/// A tile from `mask` for cell `i`, aimed at the elevation `height[i]` wants.
/// The closest class always wins; where two tiles share that class (plains and
/// ruins are both class 3) the weight decides, so ruins stay rare. Picking on
/// weight alone gives a map of static, not a world.
fn pickTile(i: usize, mask: u16) u8 {
    const want = wantClass(height[i]);
    var best_d: u8 = 255;
    var pool: u16 = 0;
    for (0..TILE_COUNT) |t| {
        if (mask & (@as(u16, 1) << @intCast(t)) == 0) continue;
        const d = @abs(@as(i32, TILES[t].cls) - @as(i32, want));
        if (d < best_d) {
            best_d = @intCast(d);
            pool = @as(u16, 1) << @intCast(t);
        } else if (d == best_d) {
            pool |= @as(u16, 1) << @intCast(t);
        }
    }
    var total: u32 = 0;
    for (0..TILE_COUNT) |t| {
        if (pool & (@as(u16, 1) << @intCast(t)) != 0) total += TILES[t].weight;
    }
    var r = rnd() % total;
    for (0..TILE_COUNT) |t| {
        if (pool & (@as(u16, 1) << @intCast(t)) == 0) continue;
        if (r < TILES[t].weight) return @intCast(t);
        r -= TILES[t].weight;
    }
    return @intCast(@ctz(pool));
}

/// Start a new world. Returns non-zero if a seed ever fails to pin the sea
/// ring, which would be a bug in the tile rules rather than a dead end.
fn reset(s: u32) u32 {
    seed = s;
    rng = s | 1;
    height_salt = s;
    buildHeight(s);
    // 0.34..0.52: some worlds are mostly archipelago, some mostly continent
    sea = 0.34 + @as(f32, @floatFromInt(rnd() % 19)) * 0.01;
    for (&masks) |*m| m.* = ALL_TILES;
    // A ring of open sea frames the map, so the land reads as an island.
    var pinned: bool = false;
    for (0..MAP_H) |y| for (0..MAP_W) |x| {
        if (x != 0 and y != 0 and x != MAP_W - 1 and y != MAP_H - 1) continue;
        masks[y * MAP_W + x] = bit(DEEP);
        if (!propagate(y * MAP_W + x)) pinned = true;
    };
    solved = false;
    return if (pinned) s else 0;
}

/// Collapse up to `budget` cells, or until the map is decided / a dead end
/// turns up. Returns the seed of a finished world, 0 if there is still work.
fn solve(budget: usize) u32 {
    var n = budget;
    while (n > 0) {
        n -= 1;
        const c = pickCell() orelse {
            for (0..CELLS) |i| world[i] = @intCast(@ctz(masks[i]));
            solved = true;
            return seed;
        };
        masks[c] = @as(u16, 1) << @intCast(pickTile(c, masks[c]));
        if (!propagate(c)) {
            // Dead end: a seed always dies the same way, so re-roll from it.
            retries += 1;
            return reset(seed +% retries *% 0x9E3779B9);
        }
    }
    return 0;
}

// -- draw -------------------------------------------------------------------

// The `:0` gives the buffer a sentinel slot, and `say` writes the NUL itself:
// std.fmt.bufPrint returns only the bytes it formatted, so slicing
// `hud[0..s.len :0]` without this would hand the host a "string" that still
// ends in the *previous* frame's text (BEACH after SHALLOWS reads BEACHSNDS).
var hud: [96:0]u8 = undefined;

fn say(comptime f: []const u8, args: anytype) [*:0]const u8 {
    const s = std.fmt.bufPrint(&hud, f, args) catch unreachable;
    hud[s.len] = 0;
    return hud[0..s.len :0];
}

fn draw() void {
    if (!solved) {
        vex.cls(C.ui_bg);
        var done: usize = 0;
        for (0..CELLS) |i| done += @intFromBool(@popCount(masks[i]) == 1);
        vex.text("COLLAPSING THE WORLD", 8, 8, C.ui_text);
        vex.rect(8, 20, 120, 4, C.ui_dim);
        vex.rect(8, 20, 120 * @divTrunc(@as(i32, @intCast(done)), @as(i32, @intCast(CELLS))), 4, C.ui_fill);
        vex.text(say("SEED {X}", .{seed}), 8, 32, C.ui_dim);
        return;
    }

    if (zoomed_out) {
        drawOverview();
        return;
    }

    const t_i: i32 = @intCast(T);
    // One tile more than the viewport needs, because the camera pans in whole
    // pixels: at cam % 16 != 0 the visible area ends part-way into an extra
    // column/row, and drawing only VIEW_W/VIEW_H leaves its last pixel line
    // showing whatever was there before. Tiles past the map edge are off-screen
    // anyway (the camera is clamped), so they are simply skipped.
    for (0..@as(usize, @intCast(VIEW_H + 1))) |r| for (0..@as(usize, @intCast(VIEW_W + 1))) |c| {
        const tx = @divTrunc(cam_x, t_i) + @as(i32, @intCast(c));
        const ty = @divTrunc(cam_y, t_i) + @as(i32, @intCast(r));
        if (tx >= MAP_W or ty >= MAP_H) continue;
        const t = world[@as(usize, @intCast(ty)) * MAP_W + @as(usize, @intCast(tx))];
        // only the sea animates; the alternate frame is a phase shift of the
        // same noise, so the water rolls instead of strobing
        const phase: usize = if (t <= SHALLOW) @intCast((tx + ty + (frame >> 4)) & 1) else 0;
        // variant keyed off the map position, so it is stable as the camera
        // scrolls -- hashing the screen position would make the ground crawl
        const v: usize = @intCast(hash(@bitCast(tx), @bitCast(ty), 0x5A5A) % VARIANTS);
        const sx = tx * t_i - cam_x;
        const sy = ty * t_i - cam_y;
        vex.blit(&TILES[t].art[v][phase], sx, sy, t_i, t_i, -1);
        // Blend in each east/south neighbour that is a different terrain, over
        // just the half of this tile facing it. Only these two sides draw, so
        // the tile earlier in row-major order owns each seam and the blend is
        // one ramp instead of two overlapping.
        if (bandsWith(t)) {
            for (BAND_DIRS) |d| {
                const nx = tx + DX[d];
                const ny = ty + DY[d];
                if (nx < 0 or ny < 0 or nx >= MAP_W or ny >= MAP_H) continue;
                const nb = world[@as(usize, @intCast(ny)) * MAP_W + @as(usize, @intCast(nx))];
                if (nb == t or !bandsWith(nb)) continue;
                // the band's blend texture has to be the variant the neighbour
                // actually draws, or every seam mismatches and the squares show
                const nv: usize = @intCast(hash(@bitCast(nx), @bitCast(ny), 0x5A5A) % VARIANTS);
                vex.blit(&BANDS[nb][dirSlot(d)][nv], sx, sy, t_i, t_i, 0); // 0 = transparent
            }
        }
    };

    // The mouse can sit below the last map row (over the HUD, or in the sliver
    // past the map at max camera), so clamp the tile we look up or this reads
    // out of bounds. Outline the pointed-at tile in white, but only while the
    // cursor is actually over the map -- otherwise it would mark a clamped
    // tile the player is not pointing at. Drawn before the HUD strip so a
    // highlight on the bottom row cannot spill onto it.
    const hx = @divTrunc(cam_x + vex.mx(), t_i);
    const hy = @min(@divTrunc(cam_y + vex.my(), t_i), @as(i32, @intCast(MAP_H)) - 1);
    if (vex.my() < HUD_Y) {
        vex.rectb(hx * t_i - cam_x, hy * t_i - cam_y, t_i, t_i, C.ui_bright);
    }

    vex.rect(0, HUD_Y, vex.WIDTH, vex.HEIGHT - HUD_Y, C.ui_bg);
    const hover: u8 = world[@as(usize, @intCast(hy)) * MAP_W + @as(usize, @intCast(hx))];
    vex.text(say("SEED {X}  {d},{d}  {s}", .{ seed, hx, hy, TILES[hover].name }), 4, HUD_Y + 2, C.ui_text);
    vex.text("ARROWS SCROLL   X MAP   Z NEW WORLD", 4, HUD_Y + 11, C.ui_dim);
}

fn input() void {
    // X used to be a fast-scroll modifier. A one-pixel-per-tile view of the
    // whole island is worth more than the speed, and a modifier nobody can see
    // is easy to forget is even there.
    if (vex.pressed(vex.X)) zoomed_out = !zoomed_out;
    const speed: i32 = 2;
    if (vex.down(vex.LEFT)) cam_x -= speed;
    if (vex.down(vex.RIGHT)) cam_x += speed;
    if (vex.down(vex.UP)) cam_y -= speed;
    if (vex.down(vex.DOWN)) cam_y += speed;
    cam_x = std.math.clamp(cam_x, 0, MAX_CAM_X);
    cam_y = std.math.clamp(cam_y, 0, MAX_CAM_Y);
    if (vex.pressed(vex.Z)) {
        retries = 0;
        _ = reset(rnd());
        cam_x = MAX_CAM_X / 2;
        cam_y = MAX_CAM_Y / 2;
    }
}

export fn boot() void {
    vex.title("vex-world");
    for (JONK16, 0..) |rgb, i| vex.pal(@intCast(i), @bitCast(rgb));
    _ = reset(seed);
    cam_x = MAX_CAM_X / 2;
    cam_y = MAX_CAM_Y / 2;
}

export fn update() void {
    frame += 1;
    input();
    if (!solved) _ = solve(GENERATE_PER_FRAME);
    draw();
}

// -- checks -----------------------------------------------------------------
// The `env` host imports only exist inside the console, so run these against
// src/env.zig, which stands in for that module (or just `make test`):
//   zig build-lib -dynamic --name env src/env.zig -lc && \
//   LD_LIBRARY_PATH=. zig test -target x86_64-linux-gnu --dep vex \
//     -Mroot=src/cart.zig -Mvex=<sdk>/vex.zig -L. -lenv

test "a solved world obeys every adjacency rule" {
    for (0..4) |trial| {
        // the sea ring must always pin; a non-zero return would mean the tile
        // rules have become unsatisfiable rather than this seed being unlucky
        try std.testing.expectEqual(@as(u32, 0), reset(0xC0FFEE +% @as(u32, @intCast(trial))));
        var guard: usize = 0;
        while (!solved and guard < 100) : (guard += 1) _ = solve(CELLS);
        try std.testing.expect(solved);
        for (0..MAP_H) |y| for (0..MAP_W) |x| {
            const i = y * MAP_W + x;
            // every cell decided, and decided on the open sea at the edges
            try std.testing.expectEqual(@as(u16, 1), @as(u16, @intCast(@popCount(masks[i]))));
            // the ring is pinned open sea; inland water is free
            if (x == 0 or y == 0 or x == MAP_W - 1 or y == MAP_H - 1) {
                try std.testing.expectEqual(DEEP, world[i]);
            }
            if (x + 1 < MAP_W) try std.testing.expect(adjacent(world[i], world[i + 1]));
            if (y + 1 < MAP_H) try std.testing.expect(adjacent(world[i], world[i + MAP_W]));
        };
    }
}

test "the same seed always collapses to the same world" {
    var first: [CELLS]u8 = undefined;
    for (0..2) |pass| {
        _ = reset(0x1234_5678);
        var guard: usize = 0;
        while (!solved and guard < 100) : (guard += 1) _ = solve(CELLS);
        try std.testing.expect(solved);
        if (pass == 0) first = world else try std.testing.expectEqualSlices(u8, &first, &world);
    }
}

test "the adjacency table is symmetric and never empty" {
    for (0..4) |d| for (0..TILE_COUNT) |a| for (0..TILE_COUNT) |b| {
        if (ALLOWED[d][a] & (@as(u16, 1) << @intCast(b)) == 0) continue;
        try std.testing.expect(ALLOWED[OPP[d]][b] & (@as(u16, 1) << @intCast(a)) != 0);
    };
    for (0..4) |d| for (0..TILE_COUNT) |a| {
        try std.testing.expect(ALLOWED[d][a] != 0);
    };
}

test "propagation only ever removes options, never adds them" {
    _ = reset(0xABCD);
    const before = masks;
    _ = solve(1);
    var narrowed: usize = 0;
    for (0..CELLS) |i| {
        try std.testing.expect(masks[i] & before[i] == masks[i]);
        if (masks[i] != before[i]) narrowed += 1;
    }
    // collapsing one cell out of 1536 has to constrain its neighbourhood,
    // otherwise propagation is not wired up at all
    try std.testing.expect(narrowed > 0);
}

test "the picked tile is allowed and as close to the aim as possible" {
    _ = reset(0x99);
    for (0..CELLS) |i| {
        // an unrestricted cell: the aim alone decides the class
        try std.testing.expectEqual(TILES[pickTile(i, ALL_TILES)].cls, wantClass(height[i]));

        // a real cell: the pick must come out of the options propagation left
        const m = masks[i];
        const t = pickTile(i, m);
        try std.testing.expect(m & (@as(u16, 1) << @intCast(t)) != 0);

        // and if the aim's class is still on the table, that is what we get
        var reachable: u8 = 255;
        for (0..TILE_COUNT) |k| {
            if (m & (@as(u16, 1) << @intCast(k)) != 0) {
                reachable = @min(reachable, TILES[k].cls);
            }
        }
        const d_want = @abs(@as(i32, wantClass(height[i])) - @as(i32, reachable));
        const d_got = @abs(@as(i32, TILES[t].cls) - @as(i32, wantClass(height[i])));
        try std.testing.expect(d_got <= d_want);
    }
}

test "the drawn tile grid covers the whole viewport at every camera offset" {
    const t: i32 = @intCast(T);
    const mw: i32 = @intCast(MAP_W);
    const mh: i32 = @intCast(MAP_H);
    // The camera scrolls in pixels, so it sits at every offset 0..15 inside a
    // tile. At a non-zero offset the viewport ends part-way into an extra
    // column/row, and a grid of exactly VIEW_W x VIEW_H tiles would leave the
    // final pixel column and row showing whatever was there before. Walk every
    // reachable camera position and check the tiles actually blitted -- the
    // in-bounds ones, since the rest are skipped -- span the full map area.
    var cam: i32 = 0;
    while (cam <= MAX_CAM_X) : (cam += 1) {
        var row: i32 = 0;
        while (row <= MAX_CAM_Y) : (row += 1) {
            const x0 = @divTrunc(cam, t);
            const y0 = @divTrunc(row, t);
            // draw() walks VIEW_W+1 / VIEW_H+1 tiles but skips any past the
            // map, so the covered strip ends at the last in-bounds tile
            const x1 = @min(x0 + VIEW_W + 1, mw);
            const y1 = @min(y0 + VIEW_H + 1, mh);
            const left = x0 * t - cam;
            const top = y0 * t - row;
            const right = x1 * t - cam;
            const bottom = y1 * t - row;
            try std.testing.expect(left <= 0);
            try std.testing.expect(top <= 0);
            try std.testing.expect(right >= vex.WIDTH);
            try std.testing.expect(bottom >= HUD_Y);
        }
    }
}

test "say() NUL-terminates, so a short string cannot inherit the previous one" {
    // the failure mode: a long name is formatted, then a shorter one. Without
    // an explicit NUL the host keeps reading into the long string's tail, so
    // "BEACH" renders as "BEACHSNDS" after "SHALLOWS".
    const long = say("SEED {X}  {d},{d}  {s}", .{ @as(u32, 0xDEADBEEF), 47, 31, "SHALLOWS" });
    try std.testing.expectEqualStrings("SEED DEADBEEF  47,31  SHALLOWS", std.mem.span(long));

    const short = say("SEED {X}  {d},{d}  {s}", .{ @as(u32, 0xDEADBEEF), 47, 31, "BEACH" });
    try std.testing.expectEqualStrings("SEED DEADBEEF  47,31  BEACH", std.mem.span(short));
    // the byte the host stops at must really be NUL
    try std.testing.expectEqual(@as(u8, 0), short[std.mem.span(short).len]);
    // and it must not have been left over from the longer string
    try std.testing.expect(!std.mem.endsWith(u8, std.mem.span(short), "SNDS"));

    // every tile name, both ways round, is NUL-terminated on its own
    for (0..TILE_COUNT) |t| {
        for (0..TILE_COUNT) |u| {
            const s = say("{s}", .{TILES[u].name});
            try std.testing.expectEqual(@as(u8, 0), s[TILES[u].name.len]);
            try std.testing.expectEqualStrings(TILES[u].name, std.mem.span(s));
            if (TILES[t].name.len > TILES[u].name.len) {
                // force a longer neighbour right before the short one
                const filler = say("{s}", .{TILES[t].name});
                try std.testing.expectEqual(@as(u8, 0), filler[TILES[t].name.len]);
            }
        }
    }
}

test "both water tiles ride one wave, and the wave tiles seamlessly" {
    // The sea animates by folding the tile's map position into `phase`, so the
    // crest has to look the same coming out of every tile. That only happens
    // when the period divides the tile size -- the original bug used a period
    // of 5 against a tile of 16, which shifted the wave in every tile and tore
    // the water along the grid.
    try std.testing.expectEqual(@as(usize, 0), T % CREST_PERIOD);

    // The two water tiles may differ in colour, never in *where* their wave
    // is: DEEP puts its crest in 9 and SHALLOWS in 10 and nothing else, so the
    // set of crest pixels has to match exactly -- in every variant and both
    // frames, since a DEEP tile can sit next to a SHALLOWS one that drew a
    // different variant.
    for (0..VARIANTS) |v| for (0..2) |ph| for (0..NP) |i| {
        const in_deep = TILES[DEEP].art[v][ph][i] == DEEP_CREST;
        const in_shallow = TILES[SHALLOW].art[v][ph][i] == SHALLOW_CREST;
        try std.testing.expectEqual(in_deep, in_shallow);
    };

    // and there has to be a wave in there, or the check above passes on two
    // blank tiles
    var crests: usize = 0;
    for (TILES[DEEP].art[0][0]) |c| crests += @intFromBool(c == DEEP_CREST);
    try std.testing.expect(crests > 0);
}

test "a seam is blended once, and only on the half facing the neighbour" {
    // The bug this pins: bands were drawn on the whole tile *and* on both sides
    // of a seam, so the two overlapped across the entire boundary. A transition
    // came out 16px wide with each terrain visible on the far side of the other
    // -- clearest where two similar terrains meet, e.g. plains into beach and
    // then beach straight back into plains.

    // 1. A band only touches the half of the tile nearest its edge, so the two
    //    halves of a seam together cover one BAND-wide transition, not two.
    for (0..TILE_COUNT) |b| {
        for (BAND_DIRS) |d| {
            var touched: usize = 0;
            for (0..T) |yy| {
                for (0..T) |xx| {
                    if (BANDS[b][dirSlot(d)][0][yy * T + xx] == 0) continue;
                    touched += 1;
                    const along: usize = switch (d) {
                        0 => yy,
                        1 => T - 1 - xx,
                        2 => T - 1 - yy,
                        else => xx,
                    };
                    try std.testing.expect(along < BAND);
                }
            }
            // it has to actually blend, or the check above passes on a blank tile
            try std.testing.expect(touched > 0);
            // and it must never flood the tile
            try std.testing.expect(touched < NP / 2);
        }
    }

    // 2. Every banding kind resolves to a real band, and those bands only ever
    //    contain art colours or the transparent 0 -- if 0 leaked in as art the
    //    blit key would punch holes in the terrain.
    try std.testing.expect(!bandsWith(RUINS));
    for (0..TILE_COUNT) |b| {
        if (!bandsWith(@intCast(b))) continue;
        for (BAND_DIRS) |d| {
            for (BANDS[b][dirSlot(d)][0]) |px| {
                // 0 is the transparency key; anything else must be real art
                try std.testing.expect(px == 0 or (px >= 1 and px <= 15));
            }
        }
    }
}

test "no seam is blended from both sides" {
    // A seam has exactly one owner: the tile earlier in row-major order, which
    // handles it on its east or south side. If a tile also banded its west and
    // north sides, both tiles would fade into each other across the same
    // boundary and the two ramps would fight -- the far terrain would spike to
    // full at the seam and then collapse back to bare inside the near tile.
    // That is why the beach/plains seam read as denser green on the beach side
    // than the plains side, and it applied to every pair, not just that one.
    //
    // BAND_DIRS carrying only east and south is the whole guarantee: for any
    // seam, exactly one of the two tiles has the other in a banding direction.
    try std.testing.expectEqual(@as(usize, 2), BAND_DIRS.len);
    for (BAND_DIRS) |d| {
        // east (1) and south (2) are exactly the two directions that point at
        // the next tile in row-major order
        try std.testing.expect(d == 1 or d == 2);
    }
    // and the opposite of each is absent, so no seam is claimed twice
    for (BAND_DIRS) |d| {
        const opposite: usize = (d + 2) % 4;
        for (BAND_DIRS) |e| try std.testing.expect(e != opposite);
    }

    // A band's ramp must run the right way round too: most of the neighbour at
    // the shared edge, least of it back inside this tile. A reversed ramp
    // reproduces the same visible artifact from the other direction.
    for (0..TILE_COUNT) |b| {
        if (!bandsWith(@intCast(b))) continue;
        for (BAND_DIRS) |d| {
            var at_edge: usize = 0;
            var at_back: usize = 0;
            for (0..T) |yy| {
                for (0..T) |xx| {
                    const along: usize = if (d == 1) T - 1 - xx else T - 1 - yy;
                    if (BANDS[b][dirSlot(d)][0][yy * T + xx] == 0) continue;
                    if (along == 0) at_edge += 1;
                    if (along + 1 == BAND) at_back += 1;
                }
            }
            // the shared edge is where the two tiles meet, so it must be the
            // most-blended line; the far end of the band is back in this tile
            try std.testing.expect(at_edge > at_back);
        }
    }
}

test "the cart has no leftover debug scaffolding" {
    // Temporary screenshot rigs kept leaking into the cart -- a pinned camera
    // silently blocked the arrow keys, a pinned cursor pinned the hover box,
    // and a stray `if (true)` swallowed the HUD gating. All three shipped
    // because nothing failed loudly: the cart still ran, it just stopped
    // responding. These are the shapes that rig took, checked at build time.
    //
    // The camera may only be written by input() (arrows, Z recentre) and by
    // boot(). Anything assigning it in update() pins movement, and a pin placed
    // after input() wins over the keys entirely.
    // Scan only the cart itself, not the checks below -- otherwise every
    // needle here would match its own literal and the test would always fail.
    const all = @embedFile("cart.zig");
    const body = all[0..std.mem.indexOf(u8, all, "// -- checks").?];

    // no unconditional branch, which is how every one of these hid in plain sight
    try std.testing.expect(std.mem.indexOf(u8, body, "if (true)") == null);
    try std.testing.expect(std.mem.indexOf(u8, body, "cam_x = 210") == null);
    try std.testing.expect(std.mem.indexOf(u8, body, "cam_y = 300") == null);
    // a hardcoded mouse read is the same bug in the hover box
    try std.testing.expect(std.mem.indexOf(u8, body, "cam_x + 137") == null);

    // the clamp has to exist, and has to sit after the arrow keys
    const clamp_at = std.mem.indexOf(u8, body, "std.math.clamp(cam_x").?;
    const last_key = std.mem.lastIndexOf(u8, body, "cam_x += speed").?;
    try std.testing.expect(clamp_at > last_key);
}

test "tile art never uses palette 0, which is the band transparency key" {
    // The transition bands blit with key 0, so a terrain pixel painted 0 would
    // be skipped and the tile underneath would show through it -- holes in the
    // map wherever the art happened to touch index 0. JONK 16's index 0 is a
    // dark blue-grey rather than black, so this is not even a colour anyone
    // would reach for deliberately; it is a silent failure.
    for (0..TILE_COUNT) |t| {
        for (0..VARIANTS) |v| for (0..2) |f| for (0..NP) |i| {
            try std.testing.expect(TILES[t].art[v][f][i] != 0);
        };
        // the bands themselves are meant to use it, and only it
        for (BANDS[t][0][0]) |px| {
            try std.testing.expect(px == 0 or (px >= 1 and px <= 15));
        }
    }
}

test "the palette table is the one the art is drawn against" {
    // 16 entries, and the roles must stay inside it
    try std.testing.expectEqual(@as(usize, 16), JONK16.len);
    inline for (@typeInfo(C).@"struct".decls) |d| {
        const v = @field(C, d.name);
        if (@TypeOf(v) != u8) continue;
        try std.testing.expect(v < 16);
    }
}
